version: 2
updates:

  # Update Dockerfile files
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    cooldown:
      default-days: 7

  # Update docker compose files
  - package-ecosystem: "docker-compose"
    directories:
      - "/support/development"
      - "/support/integration-testing"
      - "/packages/sails-hook-redbox-storage-mongo/support"
    schedule:
      interval: "daily"
    target-branch: "develop"
    cooldown:
      default-days: 7

  # Update github actions files
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    cooldown:
      default-days: 7

  # Update package npm files
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/raido"
      - "/packages/redbox-core"
      - "/packages/redbox-dev-tools"
      - "/packages/rva-registry"
      - "/packages/sails-hook-redbox-storage-mongo"
      - "/packages/sails-ng-common"
    schedule:
      interval: "daily"
    target-branch: "develop"
    cooldown:
      default-days: 7

  # Update support npm files
  - package-ecosystem: "npm"
    directories:
      - "/support/build/api-descriptors"
      - "/test/bruno"
    schedule:
      interval: "daily"
    target-branch: "develop"
    cooldown:
      default-days: 7

  # Update angular npm files
  # Update angular dependencies as a group,
  #  with one PR having minor & patch changes,
  #  and separate PR for major version changes
  - package-ecosystem: "npm"
    directories:
      - "/angular"
      - "/angular/projects/researchdatabox/portal-ng-common"
      - "/angular/projects/researchdatabox/portal-ng-form-custom"
    schedule:
      interval: "daily"
    target-branch: "develop"
    groups:
      angular:
        applies-to: "version-updates"
        patterns:
          - "@angular*"
          - "ngx-bootstrap"
          - "angular-i18next"
          - "@schematics/angular"
          - "ng-packagr"
          - "@ngx-formly/*"
        update-types:
          - "minor"
          - "patch"
      angular-major:
        applies-to: "version-updates"
        patterns:
          - "@angular*"
          - "ngx-bootstrap"
          - "angular-i18next"
          - "@schematics/angular"
          - "ng-packagr"
          - "@ngx-formly/*"
        update-types:
          - "major"
    cooldown:
      default-days: 7
