version: '2'
services:
  dlcfportal:
    image: qcifengineering/dlcf-portal:latest
    ports:
       - "1500:1500"
    expose:
       - "1500"
    environment:
      - NODE_ENV=development
      - PORT=1500
      - sails_ng2__force_bundle=true
    links:
      - mongodb:mongodb
      - redbox:redbox
    entrypoint: /bin/bash -c "cd /opt/rds-rdmp-portal && node app.js"
  mongodb:
    image: mvertes/alpine-mongo:latest
    ports:
       - "27017:27017"
  redbox:
    image: qcifengineering/dlcf-redbox
    ports:
       - "9000:9000"
