/* tslint:disable */
/* eslint-disable */
/**
 * Vocabulary Registry API
 * Public access to the Vocabulary Registry API
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: services@ardc.edu.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

