import { expect, test } from '../fixtures/test';
import { field, saveForm } from '../helpers/forms';

test('F11 validation fields-cross-field errors block persistence and clear on correction', async ({ adminPage, records }) => {
  const record = await records.create('e2e-validation-fields-cross-field', { title: 'Validation', requiredValue: 'Required', email: 'original@example.test', left: 'A', right: 'B' });
  await adminPage.goto(`/default/rdmp/record/edit/${record.oid}`);
  const summary = adminPage.locator('redbox-validation-summary-field');
  await field(adminPage, 'Required value').clear();
  await field(adminPage, 'Email').fill('invalid');
  await field(adminPage, 'Second code').fill('A');
  await expect(summary).toContainText('Required value is missing');
  await expect(summary).toContainText('Enter a valid email address');
  await expect(summary).toContainText('The two codes must differ');
  await expect(adminPage.getByRole('button', { name: 'Save', exact: true })).toBeDisabled();
  expect((await records.read(record.oid)).body).toMatchObject({ requiredValue: 'Required', email: 'original@example.test', right: 'B' });
  await field(adminPage, 'Required value').fill('Corrected');
  await field(adminPage, 'Email').fill('corrected@example.test');
  await field(adminPage, 'Second code').fill('C');
  await expect(summary.locator('[role="alert"]')).toHaveCount(0);
  await saveForm(adminPage);
  await adminPage.reload();
  await expect(field(adminPage, 'Email')).toHaveValue('corrected@example.test');
  expect((await records.read(record.oid)).body).toMatchObject({ requiredValue: 'Corrected', right: 'C' });
});

test('F12 validation groups switch all, none, selected and conditional membership immediately', async ({ adminPage, records }) => {
  const record = await records.create('e2e-validation-groups', { title: 'Groups', mode: 'none', extra: 'no', requiredValue: '', conditionalValue: '' });
  await adminPage.goto(`/default/rdmp/record/edit/${record.oid}`);
  const errors = adminPage.locator('redbox-validation-summary-field [data-validation-error-class]');
  const mode = field(adminPage, 'Validation mode');
  const save = adminPage.getByRole('button', { name: 'Save', exact: true });
  await mode.fill('all');
  await expect(errors).toHaveCount(2);
  await expect(save).toBeDisabled();
  await mode.fill('none');
  await expect(errors).toHaveCount(0);
  await expect(save).toBeEnabled();
  await mode.fill('selected');
  await expect(errors).toHaveCount(1);
  await expect(errors).toHaveText('Selected group requires a value');
  await field(adminPage, 'Required value').fill('Selected group satisfied');
  await expect(errors).toHaveCount(0);
  await mode.fill('conditional');
  await field(adminPage, 'Enable conditional group').fill('yes');
  await expect(errors).toHaveCount(1);
  await expect(errors).toHaveText('Conditional group requires a value');
  await expect(save).toBeDisabled();
  await field(adminPage, 'Enable conditional group').fill('no');
  await expect(errors).toHaveCount(0);
  await expect(save).toBeEnabled();
  await saveForm(adminPage);
  expect((await records.read(record.oid)).body).toMatchObject({ mode: 'conditional', extra: 'no', requiredValue: 'Selected group satisfied' });
});

test('F13 validation summaries reveal hidden fields while advisory errors permit saving', async ({ adminPage, records }) => {
  const record = await records.create('e2e-validation-summaries', { title: 'Summaries', requiredValue: 'Valid', tabValue: 'Valid', panelValue: 'Valid', advisoryValue: '' });
  await adminPage.goto(`/default/rdmp/record/edit/${record.oid}`);
  await adminPage.getByRole('tab', { name: 'Details', exact: true }).click();
  await field(adminPage, 'Hidden tab value').clear();
  await adminPage.getByRole('tab', { name: 'Overview', exact: true }).click();
  await adminPage.getByRole('button', { name: 'More details', exact: true }).click();
  await field(adminPage, 'Closed panel value').clear();
  await adminPage.getByRole('button', { name: 'More details', exact: true }).click();
  await field(adminPage, 'Required value').clear();
  const summary = adminPage.locator('redbox-validation-summary-field');
  await expect(summary.locator('[data-validation-error-class]')).toHaveCount(3);
  await expect(adminPage.getByRole('button', { name: 'Save', exact: true })).toBeDisabled();
  await summary.getByRole('link', { name: /Hidden tab value/ }).click();
  await expect(adminPage.getByRole('tab', { name: 'Details', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(field(adminPage, 'Hidden tab value')).toBeFocused();
  await field(adminPage, 'Hidden tab value').fill('Tab corrected');
  await summary.getByRole('link', { name: /Closed panel value/ }).click();
  await expect(adminPage.getByRole('button', { name: 'More details', exact: true })).toHaveAttribute('aria-expanded', 'true');
  await expect(field(adminPage, 'Closed panel value')).toBeFocused();
  await field(adminPage, 'Closed panel value').fill('Panel corrected');
  await summary.getByRole('link', { name: /Required value/ }).click();
  await expect(field(adminPage, 'Required value')).toBeFocused();
  await field(adminPage, 'Required value').fill('Ordinary corrected');
  await expect(summary.locator('[data-validation-error-class]')).toHaveCount(0);
  await expect(adminPage.locator('redbox-suggested-validation-summary-field')).toContainText('A recommendation remains');
  const saved = adminPage.waitForResponse(response => response.request().method() === 'PUT' && new URL(response.url()).pathname === `/default/rdmp/recordmeta/${record.oid}`);
  await adminPage.getByRole('button', { name: 'Save', exact: true }).click();
  const response = await saved;
  expect(response.ok()).toBeTruthy();
  const { meta: body } = await response.json();
  expect(body.outcome).toBe('saved-with-warnings');
  expect(body.problems).toEqual([expect.objectContaining({ kind: 'validation', issues: [expect.objectContaining({ pointer: '/advisoryValue' })] })]);
  await expect(adminPage.locator('redbox-form-save-status [role="alert"]')).toContainText('Your changes were saved');
  expect((await records.read(record.oid)).body).toMatchObject({ tabValue: 'Tab corrected', panelValue: 'Panel corrected', advisoryValue: '' });
});

test('F14 validation repeatables keep error counts and focus targets attached to current rows', async ({ adminPage, records }) => {
  const record = await records.create('e2e-validation-repeatables', { title: 'Contacts', rows: [{ label: 'Alpha', email: 'alpha@example.test' }, { label: 'Beta', email: 'beta@example.test' }] });
  await adminPage.goto(`/default/rdmp/record/edit/${record.oid}`);
  const rows = adminPage.locator('redbox-form-repeatable .rb-form-repeatable-item');
  const summary = adminPage.locator('redbox-validation-summary-field');
  const errors = summary.locator('[data-validation-error-class]');
  await expect(rows).toHaveCount(2);
  await adminPage.locator('redbox-form-repeatable').getByRole('button', { name: /add/i }).click();
  await expect(rows).toHaveCount(3);
  await expect(errors).toHaveCount(1);
  await field(rows.nth(0), 'Contact email').clear();
  await expect(errors).toHaveCount(2);
  await field(rows.nth(0), 'Contact email').fill('corrected@example.test');
  await expect(errors).toHaveCount(1);
  await rows.nth(2).getByRole('button', { name: /remove/i }).click();
  await expect(errors).toHaveCount(0);
  await field(rows.nth(1), 'Contact email').fill('invalid');
  await expect(errors).toHaveCount(1);
  await rows.nth(0).getByRole('button', { name: /remove/i }).click();
  await expect(rows).toHaveCount(1);
  await expect(errors).toHaveCount(1);
  await summary.getByRole('link', { name: /Contact email/ }).click();
  await expect(field(rows.nth(0), 'Contact email')).toBeFocused();
  await field(rows.nth(0), 'Contact email').fill('survivor@example.test');
  await expect(errors).toHaveCount(0);
  await saveForm(adminPage);
  await adminPage.reload();
  await expect(rows).toHaveCount(1);
  await expect(field(rows.nth(0), 'Contact email')).toHaveValue('survivor@example.test');
  expect((await records.read(record.oid)).body).toMatchObject({ rows: [{ label: 'Beta', email: 'survivor@example.test' }] });
});

test('F15 validation save-operations restore ordinary groups after success, rejection and transport failure', async ({ adminPage, records, diagnostics }) => {
  const record = await records.create('e2e-validation-save-operations', { title: 'Operations', ordinaryValue: 'Ordinary valid', submitValue: 'Submission valid' });
  await adminPage.goto(`/default/rdmp/record/edit/${record.oid}`);
  const ordinary = field(adminPage, 'Ordinary required value');
  const submit = field(adminPage, 'Submission value');
  const ordinarySave = adminPage.getByRole('button', { name: 'Save', exact: true });
  const saveUrl = new RegExp(`/recordmeta/${record.oid}(?:\\?|$)`);
  const restored = async () => {
    await ordinary.clear();
    await expect(adminPage.locator('redbox-validation-summary-field')).toContainText('Ordinary validation restored');
    await expect(ordinarySave).toBeDisabled();
    await ordinary.fill('Ordinary restored');
    await expect(ordinarySave).toBeEnabled();
  };
  await submit.clear();
  await adminPage.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(adminPage.locator('redbox-form-save-status .alert-success')).toBeVisible();
  await restored();
  diagnostics.expectFailure({ kind: 'response', method: 'PUT', url: saveUrl, status: 400, count: 1, reason: 'The browser save endpoint returns 400 for real submission validation rejection.' });
  diagnostics.expectFailure({ kind: 'console', url: saveUrl, message: /Failed to load resource.*400/, count: 1, reason: 'Chromium reports the same rejected submit.' });
  const rejected = adminPage.waitForResponse(response => response.request().method() === 'PUT' && response.url().endsWith(`${record.oid}?operation=submit`));
  await adminPage.getByRole('button', { name: 'Submit for validation', exact: true }).click();
  expect((await (await rejected).json()).meta.problems).toEqual([expect.objectContaining({ kind: 'validation', issues: [expect.objectContaining({ pointer: '/submitValue' })] })]);
  await expect(adminPage.locator('redbox-form-save-status [role="alert"]')).toBeVisible();
  await restored();
  const abortSave = async (route: import('@playwright/test').Route) => { await route.abort('failed'); };
  diagnostics.expectFailure({ kind: 'requestfailed', method: 'PUT', url: saveUrl, message: /net::ERR_FAILED/, count: 1, reason: 'Explicit pre-dispatch save fault verifies operation cleanup.' });
  diagnostics.expectFailure({ kind: 'console', url: saveUrl, message: /Failed to load resource.*ERR_FAILED/, count: 1, reason: 'Chromium reports the explicitly aborted save.' });
  await adminPage.route(saveUrl, abortSave);
  try {
    await adminPage.getByRole('button', { name: 'Save draft', exact: true }).click();
    await expect(adminPage.locator('redbox-form-save-status [role="alert"]')).toBeVisible();
  } finally { await adminPage.unroute(saveUrl, abortSave); }
  await restored();
  await submit.fill('Submission recovered');
  await adminPage.getByRole('button', { name: 'Submit for validation', exact: true }).click();
  await expect(adminPage.locator('redbox-form-save-status .alert-success')).toBeVisible();
  await adminPage.reload();
  await expect(submit).toHaveValue('Submission recovered');
  expect((await records.read(record.oid)).body).toMatchObject({ submitValue: 'Submission recovered', ordinaryValue: 'Ordinary restored' });
});
