/**
 * Sails hook for redbox-core-types integration.
 * 
 * This hook generates model, service and controller shim files from the classes
 * exported by @researchdatabox/redbox-core-types. The shims are generated before
 * the ORM hook loads, allowing Sails to use the TypeScript-defined implementations.
 */

const fs = require('fs');
const path = require('path');
const { WaterlineModels, SailsServices, SailsControllers, WebserviceControllers } = require('@researchdatabox/redbox-core-types');

// Models that are provided by external hooks (e.g., sails-hook-redbox-storage-mongo)
// These are copied at runtime and should not be overwritten
const EXTERNAL_MODELS = ['Record', 'DeletedRecord', 'RecordAudit'];

function generateModelShims(sails, modelsDir) {
  const modelNames = Object.keys(WaterlineModels);
  let generated = 0;
  let skipped = 0;

  for (const name of modelNames) {
    // Skip models provided by external hooks
    if (EXTERNAL_MODELS.includes(name)) {
      sails.log.verbose(`redbox-core-loader: Skipping ${name} (provided by external hook)`);
      skipped++;
      continue;
    }

    const filePath = path.join(modelsDir, `${name}.js`);
    const content = `'use strict';
/**
 * ${name} model shim
 * Auto-generated by api/hooks/redbox-core-loader
 * Do not edit manually - regenerated on each app start
 */
const { WaterlineModels } = require('@researchdatabox/redbox-core-types');
module.exports = { ...WaterlineModels['${name}'], globalId: '${name}' };
`;

    fs.writeFileSync(filePath, content, 'utf8');
    generated++;
  }

  return { generated, skipped };
}

function generateServiceShims(sails, servicesDir) {
  const serviceNames = Object.keys(SailsServices);
  let generated = 0;

  for (const name of serviceNames) {
    const filePath = path.join(servicesDir, `${name}.js`);

    // Check if file exists and is NOT a shim
    if (fs.existsSync(filePath)) {
      const existingContent = fs.readFileSync(filePath, 'utf8');
      if (!existingContent.includes('Auto-generated by api/hooks/redbox-core-loader')) {
        sails.log.verbose(`redbox-core-loader: Skipping ${name} (local implementation found)`);
        continue;
      }
    }

    const content = `'use strict';
/**
 * ${name} service shim
 * Auto-generated by api/hooks/redbox-core-loader
 * Do not edit manually - regenerated on each app start
 */
const { SailsServices } = require('@researchdatabox/redbox-core-types');
module.exports = new SailsServices['${name}']().exports();
`;

    fs.writeFileSync(filePath, content, 'utf8');
    generated++;
  }

  return { generated };
}

function generateControllerShims(sails, controllersDir, webserviceDir) {
  const controllerNames = Object.keys(SailsControllers);
  const webserviceNames = Object.keys(WebserviceControllers);
  let generated = 0;

  // Main controllers
  for (const name of controllerNames) {
    const filePath = path.join(controllersDir, `${name}.js`);
    const content = `'use strict';
/**
 * ${name} controller shim
 * Auto-generated by api/hooks/redbox-core-loader
 * Do not edit manually - regenerated on each app start
 */
const { SailsControllers } = require('@researchdatabox/redbox-core-types');
module.exports = new SailsControllers['${name}']().exports();
`;

    fs.writeFileSync(filePath, content, 'utf8');
    generated++;
  }

  // Webservice controllers
  for (const name of webserviceNames) {
    const filePath = path.join(webserviceDir, `${name}.js`);
    const content = `'use strict';
/**
 * webservice/${name} controller shim
 * Auto-generated by api/hooks/redbox-core-loader
 * Do not edit manually - regenerated on each app start
 */
const { WebserviceControllers } = require('@researchdatabox/redbox-core-types');
module.exports = new WebserviceControllers['${name}']().exports();
`;

    fs.writeFileSync(filePath, content, 'utf8');
    generated++;
  }

  return { generated };
}

module.exports = function redboxCoreLoader(sails) {
  return {
    defaults: {
      __configKey__: {
        enabled: true,
      }
    },

    configure: function () {
      if (!sails.config[this.configKey].enabled) {
        sails.log.verbose('redbox-core-loader: Disabled via config');
        return;
      }

      const modelCount = Object.keys(WaterlineModels).length;
      const serviceCount = Object.keys(SailsServices).length;
      const controllerCount = Object.keys(SailsControllers).length;
      const webserviceCount = Object.keys(WebserviceControllers).length;

      sails.log.verbose(`redbox-core-loader: ${modelCount} models, ${serviceCount} services, ${controllerCount} controllers, ${webserviceCount} webservice controllers available from @researchdatabox/redbox-core-types`);

      // Generate model shims before ORM loads them
      const modelsDir = path.resolve(__dirname, '../../models');
      if (!fs.existsSync(modelsDir)) {
        fs.mkdirSync(modelsDir, { recursive: true });
      }
      const modelStats = generateModelShims(sails, modelsDir);
      sails.log.verbose(`redbox-core-loader: Generated ${modelStats.generated} model shims, skipped ${modelStats.skipped} external models`);

    },

    initialize: function (done) {
      sails.log.verbose('redbox-core-loader: Initialization complete');
      return done();
    }
  };
};
