/**
 * Sails hook for redbox-core-types integration.
 * 
 * This hook generates model, service and controller shim files from the classes
 * exported by @researchdatabox/redbox-core-types. The shims are generated before
 * the ORM hook loads, allowing Sails to use the TypeScript-defined implementations.
 */

const fs = require('fs');
const path = require('path');
const { WaterlineModels } = require('@researchdatabox/redbox-core-types');

// Models that are provided by external hooks (e.g., sails-hook-redbox-storage-mongo)
// These are copied at runtime and should not be overwritten
const EXTERNAL_MODELS = ['Record', 'DeletedRecord', 'RecordAudit'];

function generateModelShims(sails, modelsDir) {
  const modelNames = Object.keys(WaterlineModels);
  let generated = 0;
  let skipped = 0;

  for (const name of modelNames) {
    // Skip models provided by external hooks
    if (EXTERNAL_MODELS.includes(name)) {
      sails.log.verbose(`redbox-core-loader: Skipping ${name} (provided by external hook)`);
      skipped++;
      continue;
    }

    const filePath = path.join(modelsDir, `${name}.js`);
    const content = `'use strict';
/**
 * ${name} model shim
 * Auto-generated by api/hooks/redbox-core-loader
 * Do not edit manually - regenerated on each app start
 */
const { WaterlineModels } = require('@researchdatabox/redbox-core-types');
module.exports = { ...WaterlineModels['${name}'], globalId: '${name}' };
`;

    fs.writeFileSync(filePath, content, 'utf8');
    generated++;
  }

  return { generated, skipped };
}


module.exports = function redboxCoreLoader(sails) {
  return {
    defaults: {
      __configKey__: {
        enabled: true,
      }
    },

    configure: function () {
      if (!sails.config[this.configKey].enabled) {
        sails.log.verbose('redbox-core-loader: Disabled via config');
        return;
      }

      const modelCount = Object.keys(WaterlineModels).length;

      sails.log.verbose(`redbox-core-loader: ${modelCount} models available from @researchdatabox/redbox-core-types`);

      // Generate model shims before ORM loads them
      const modelsDir = path.resolve(__dirname, '../../models');
      if (!fs.existsSync(modelsDir)) {
        fs.mkdirSync(modelsDir, { recursive: true });
      }
      const modelStats = generateModelShims(sails, modelsDir);
      sails.log.verbose(`redbox-core-loader: Generated ${modelStats.generated} model shims, skipped ${modelStats.skipped} external models`);

    },

    initialize: function (done) {
      sails.log.verbose('redbox-core-loader: Initialization complete');
      return done();
    }
  };
};
