/**
 * Sails hook for redbox-core-types integration.
 * 
 * This hook generates model, service and controller shim files from the classes
 * exported by @researchdatabox/redbox-core-types. The shims are generated before
 * the ORM hook loads, allowing Sails to use the TypeScript-defined implementations.
 * 
 * External hooks can register their own typed models by adding them to
 * sails.config.redboxHookModels in their configure() phase.
 */

const fs = require('fs');
const path = require('path');
const { WaterlineModels } = require('@researchdatabox/redbox-core-types');

// Models that are provided by external hooks (legacy compatibility)
// These are skipped from core WaterlineModels unless registered via sails.config.redboxHookModels
const EXTERNAL_MODELS = ['Record', 'DeletedRecord', 'RecordAudit'];

function generateModelShims(sails, modelsDir) {
  // Get hook-registered models from sails.config
  const hookModels = sails.config.redboxHookModels || {};

  // First, collect all model names from both sources
  const coreModelNames = Object.keys(WaterlineModels);
  const hookModelNames = Object.keys(hookModels);
  const allModelNames = new Set([...coreModelNames, ...hookModelNames]);

  let generated = 0;
  let skipped = 0;
  let fromHooks = 0;

  for (const name of allModelNames) {
    // Check if this model is registered by a hook
    if (hookModels[name]) {
      // Generate shim from hook-provided model
      const filePath = path.join(modelsDir, `${name}.js`);
      const modelDef = hookModels[name];
      const content = `'use strict';
/**
 * ${name} model shim
 * Auto-generated by api/hooks/redbox-core-loader
 * Provided by: hook registration (sails.config.redboxHookModels)
 * Do not edit manually - regenerated on each app start
 */
module.exports = ${JSON.stringify({ ...modelDef, globalId: name }, null, 2)};
`;
      fs.writeFileSync(filePath, content, 'utf8');
      generated++;
      fromHooks++;
      continue;
    }

    // Skip external models that aren't registered via hooks (legacy compatibility)
    if (EXTERNAL_MODELS.includes(name)) {
      sails.log.verbose(`redbox-core-loader: Skipping ${name} (legacy external model, not registered)`);
      skipped++;
      continue;
    }

    // Generate shim from core WaterlineModels
    if (WaterlineModels[name]) {
      const filePath = path.join(modelsDir, `${name}.js`);
      const content = `'use strict';
/**
 * ${name} model shim
 * Auto-generated by api/hooks/redbox-core-loader
 * Provided by: @researchdatabox/redbox-core-types
 * Do not edit manually - regenerated on each app start
 */
const { WaterlineModels } = require('@researchdatabox/redbox-core-types');
module.exports = { ...WaterlineModels['${name}'], globalId: '${name}' };
`;
      fs.writeFileSync(filePath, content, 'utf8');
      generated++;
    }
  }

  return { generated, skipped, fromHooks };
}

module.exports = function redboxCoreLoader(sails) {
  return {
    defaults: {
      __configKey__: {
        enabled: true,
      },
      // Initialize the redboxHookModels config for hooks to populate
      redboxHookModels: {}
    },

    configure: function () {
      if (!sails.config[this.configKey].enabled) {
        sails.log.verbose('redbox-core-loader: Disabled via config');
        return;
      }

      const coreModelCount = Object.keys(WaterlineModels).length;
      sails.log.verbose(`redbox-core-loader: ${coreModelCount} core models available from @researchdatabox/redbox-core-types`);

      // Generate model shims before ORM loads them
      // Note: At configure time, other hooks may not have registered their models yet,
      // so we generate core models now and hook models will be handled by the hook's own mechanism
      const modelsDir = path.resolve(__dirname, '../../models');
      if (!fs.existsSync(modelsDir)) {
        fs.mkdirSync(modelsDir, { recursive: true });
      }
      const modelStats = generateModelShims(sails, modelsDir);
      sails.log.verbose(`redbox-core-loader: Generated ${modelStats.generated} model shims (${modelStats.fromHooks} from hooks), skipped ${modelStats.skipped} external`);
    },

    initialize: function (done) {
      sails.log.verbose('redbox-core-loader: Initialization complete');
      return done();
    }
  };
};

