name: pdfgen-bruno

networks:
  main:

x-rbportal-env: &rbportal-env
  - NODE_ENV=integrationtest
  - NODE_PATH=/opt/redbox-portal/node_modules:/opt/redbox-portal/node_modules/@researchdatabox/redbox-core/node_modules
  - PORT=1500
  - sails_redbox__mochaTesting=true
  - sails_security__csrf=false
  - LOAD_DEFAULT_FORMS=true
  - sails_brandingConfigurationDefaults__auth__local__default__token=6b088b4d-d54c-470c-8568-2f2695fcdab9
  - sails_brandingConfigurationDefaults__pdfgen__token=6b088b4d-d54c-470c-8568-2f2695fcdab9
  - CI=${CI:-false}
  - RBPORTAL_COVERAGE_DIR=/tmp/coverage/mocha

x-rbportal-depends: &rbportal-depends
  mongodb:
    condition: service_healthy
  solr:
    condition: service_healthy

services:
  bruno:
    image: node:24.14.1-bookworm
    pull_policy: "missing"
    volumes:
      - "../../.tmp/junit/backend-bruno:/opt/junit/backend-bruno"
      - "../../test/bruno:/opt/bruno-tests"
    working_dir: /opt/bruno-tests
    depends_on:
      redboxportal:
        condition: service_healthy
    networks:
      main:
        aliases:
          - bruno
    entrypoint: >-
      /bin/sh -lc "cd /opt/bruno-tests &&
      npm ci --ignore-scripts &&
      node_modules/.bin/bru run
      --env test
      --format junit
      --output /opt/junit/backend-bruno/backend-bruno.xml
      --bail"

  redboxportal:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: redbox-hook--researchdatabox-sails-hook-redbox-pdfgen
    ports:
      - "1500:1500"
    volumes:
      - "../../:/opt/redbox-portal/node_modules/@researchdatabox/sails-hook-redbox-pdfgen:delegated"
      - "./recordtype.config.js:/opt/redbox-portal/node_modules/@researchdatabox/redbox-core/dist/config/recordtype.config.js:delegated"
    depends_on: *rbportal-depends
    expose:
      - "1500"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:1500/default/rdmp/home"]
      interval: "10s"
      timeout: "5s"
      retries: 10
      start_period: "60s"
    environment: *rbportal-env
    networks:
      main:
        aliases:
          - redboxportal
          - rbportal
    init: true
    entrypoint: >-
      /bin/bash -c "set -x;
      cd /opt/redbox-portal &&
      node --enable-source-maps app.js;"

  mongodb:
    image: mongo:7
    networks:
      main:
        aliases:
          - mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", 'echo ''db.runCommand("ping").ok'' | mongosh']
      interval: "10s"
      timeout: "5s"
      retries: 10
      start_period: "30s"

  solr:
    image: solr:8.11.1
    expose:
      - "8983"
    ports:
      - "8983:8983"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8983"]
      interval: "10s"
      timeout: "5s"
      retries: 10
      start_period: "30s"
    networks:
      main:
        aliases:
          - solr
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - redbox
