networks:
  main:

services:

  redbox:
    stop_grace_period: 30s
    init: true
    expose:
      - '1500'
    ports:
      - '1500:1500'
    environment:
      - 'NODE_ENV=docker'
      - 'PORT=1500'
      - 'sails_admin__api_token=6b088b4d-d54c-470c-8568-2f2695fcdab9'
      - 'sails_auth__default__local__default__token=6b088b4d-d54c-470c-8568-2f2695fcdab9'
      - 'sails_auth__default__local_pdfbot_token=6b088b4d-d54c-470c-8568-2f2695fcdab9'
      - 'sails_redbox__apiKey=6b088b4d-d54c-470c-8568-2f2695fcdab9'
      - 'sails_record__baseUrl__redbox=http://redbox:9000/redbox'
      - 'sails_record__baseUrl__mint=https://demo.redboxresearchdata.com.au/mint'
      - 'HOOK_S3_ACCESS_KEY=minioadmin'
      - 'HOOK_S3_SECRET_KEY=minioadmin'
      - 'HOOK_S3_REGION=ap-southeast-2'
      - 'HOOK_S3_BUCKET=attachments'
      - 'HOOK_S3_ENDPOINT=http://minio:9000'
      - 'sails_log__level=verbose'
      # For NG apps migrated NG 15 or above, if you are actively developing the front-end, then build your app manually, making sure you disable filename hashing, before you use the app.
      - 'sails_angularDev=true'
      # Flag to enable the new form framework app, currently enabled in the "edit" mode
      - 'sails_enableNewForm=true'
    healthcheck:
      test: [ 'CMD-SHELL', 'curl http://localhost:1500/default/rdmp/home' ]
      interval: '15s'
      timeout: '5s'
      retries: 10
      start_period: '30s'
    networks:
      main:
        aliases:
          - redbox
    depends_on:
      minio:
        condition: 'service_healthy'
      mongodb:
        condition: 'service_healthy'
      solr:
        condition: 'service_healthy'
      email:
        condition: 'service_healthy'

  minio:
    image: 'quay.io/minio/minio:latest'
    command: ['server','/data','--console-address',':9002']
    expose:
      - '9000'
      - '9002'
    ports:
      - '9000:9000'
      - '9002:9002'
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
    healthcheck:
      test: [ 'CMD-SHELL', 'curl http://localhost:9000' ]
      interval: '5s'
      timeout: '5s'
      retries: 10
      start_period: '20s'
    networks:
      main:
        aliases:
          - minio

  mongodb:
    image: 'mongo:latest'
    expose:
      - '27017'
    ports:
      - '27017:27017'
    healthcheck:
      test: [ 'CMD-SHELL', "echo 'db.runCommand(\"ping\").ok' | mongosh" ]
      interval: '15s'
      timeout: '5s'
      retries: 10
      start_period: '30s'
    networks:
      main:
        aliases:
          - mongodb

  solr:
    image: 'solr:latest'
    expose:
      - '8983'
    ports:
      - '8983:8983'
    environment:
      - 'SOLR_HOME=/var/solr/data'
    healthcheck:
      test: [ 'CMD-SHELL', 'curl http://localhost:8983' ]
      interval: '15s'
      timeout: '5s'
      retries: 10
    networks:
      main:
        aliases:
          - solr
    entrypoint:
      - 'docker-entrypoint.sh'
      - 'solr-precreate'
      - 'redbox'

  email:
    image: 'axllent/mailpit:latest'
    expose:
      - '1025'
      - '8025'
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: '/data/mailpit.db'
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      TZ: 'Australia/Brisbane'
    networks:
      main:
        aliases:
          - email