"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let expect;
import("chai").then(mod => expect = mod.expect);
describe('The FormsService', function () {
    before(function (done) {
        done();
    });
    it('should return the default RDMP form', function (done) {
        var brand = BrandingService.getDefault();
        var recordType = 'rdmp';
        var formName = 'default-1.0-draft';
        RecordType.find().then(forms => {
            sails.log.verbose(`going to look for ${brand.id}_${recordType}`);
            sails.log.verbose(forms);
        });
        console.log('brand.id ' + brand.id + ' recordType ' + recordType);
        FormsService.getFormByStartingWorkflowStep(brand, recordType, true).subscribe(function (form) {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should get dataPublication-1.0-embargoed form', function (done) {
        var formName = 'dataPublication-1.0-embargoed';
        FormsService.getFormByName(formName, true).subscribe(function (form) {
            console.log(form);
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should return the form based of a given record', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'default-1.0-draft';
        let record = {
            metaMetadata: {
                form: formName,
                type: 'rdmp'
            }
        };
        FormsService.getForm(brand, '', true, '', record).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should return the autogenerated form based of a given record', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'generated-view-only';
        let record = {
            metaMetadata: {
                form: formName,
                type: 'rdmp'
            },
            metadata: {
                ID: 's823456',
                GIVEN_NAME: 'Ant10',
                OTHER_NAMES: 'Other',
                FAMILY_NAME: 'Season',
                PREF_NAME: 'Ant',
                HONORIFIC: 'Sr',
                EMAIL: 'notAReal@email.edu.au',
                JOB_TITLE: 'Assistant Professor',
                NLA_PARTY_IDENTIFIER: '',
                URIs: ['URI1', 'URI2', 'URI3'],
                ORCID: '0000-0001-7269-2286',
                PERSONAL_HOMEPAGE: '',
                STAFF_PROFILE_HOMEPAGE: '',
                DESCRIPTION: '',
                RESEARCH_ELEMENTS_USER_ID: '12345678',
                contributor_ci: {
                    text_full_name: 'Prof Ant10 Season',
                    email: 'notAReal@email.edu.au',
                    orcid: 'http://orcid.org/0000-0000-0000-000'
                },
                contributor_data_manager: [{
                        text_full_name: 'Prof Ant Season',
                        email: 'notAReal@email.edu.au',
                        orcid: 'http://orcid.org/0000-0000-0000-000'
                    }]
            }
        };
        FormsService.getForm(brand, '', true, '', record).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should return the form', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'default-1.0-draft';
        FormsService.getForm(brand, formName, true, 'rdmp', {}).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should return the autogenerated form', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'generated-view-only';
        FormsService.getForm(brand, formName, true, 'rdmp', {}).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    describe("build client form config", function () {
        it('should build the expected config', function (done) {
            const formConfig = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        constraints: {
                            authorization: {
                                allowRoles: [],
                            },
                            allowModes: [],
                        },
                    }
                ]
            };
            const expected = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                value: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                    }
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = FormsService.buildClientFormConfig(formConfig);
            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);
            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
            done();
        });
        it('should remove the component because the user does not have the required roles', function (done) {
            const formConfig = {
                name: "remove-item-constraint-roles",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                        },
                    },
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        constraints: {
                            authorization: {
                                allowRoles: ['Admin', 'Librarians'],
                            },
                            allowModes: [],
                        },
                    }
                ]
            };
            const expected = {
                name: "remove-item-constraint-roles",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                        },
                    }
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = FormsService.buildClientFormConfig(formConfig);
            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);
            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
            done();
        });
        it('should remove the component because the client does not have the required mode', function (done) {
            const formConfig = {
                name: "remove-item-constraint-mode",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                        },
                    },
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        expressions: {
                            'model.value': {
                                template: `<%= _.get(model,'text_1_event','') %>`
                            }
                        },
                        constraints: {
                            authorization: {
                                allowRoles: [],
                            },
                            allowModes: ['edit'],
                        },
                    }
                ]
            };
            const expected = {
                name: "remove-item-constraint-mode",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                        },
                    },
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = FormsService.buildClientFormConfig(formConfig);
            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);
            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
            done();
        });
        it('should remove the components nested in repeatable and group components when the constraints are not met', function (done) {
            const formConfig = {
                name: "remove-items-constrains-nested",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'repeatable_group_1',
                        model: {
                            class: 'RepeatableModel',
                            config: { defaultValue: [{ text_1: "hello world from repeating groups" }] }
                        },
                        component: {
                            class: 'RepeatableComponent',
                            config: {
                                elementTemplate: {
                                    name: null,
                                    model: { class: 'GroupModel', config: { defaultValue: {} } },
                                    component: {
                                        class: 'GroupComponent',
                                        config: {
                                            wrapperCssClasses: 'col',
                                            componentDefinitions: [
                                                {
                                                    // requires mode edit, so expect to be removed
                                                    name: 'text_1',
                                                    model: {
                                                        class: 'SimpleInputModel',
                                                        config: { defaultValue: 'hello world 1!', }
                                                    },
                                                    component: { class: 'SimpleInputComponent' },
                                                    constraints: { allowModes: ['edit'] },
                                                },
                                                {
                                                    name: 'text_2',
                                                    model: { class: 'SimpleInputModel', config: { defaultValue: 'hello world 2!' } },
                                                    component: { class: 'SimpleInputComponent' },
                                                },
                                                {
                                                    // requires role 'Admin', so is removed
                                                    name: 'repeatable_for_admin',
                                                    model: { class: 'RepeatableModel', config: {} },
                                                    component: {
                                                        class: 'RepeatableComponent',
                                                        config: {
                                                            elementTemplate: {
                                                                name: null,
                                                                model: {
                                                                    class: 'SimpleInputModel',
                                                                    config: { defaultValue: 'hello world from repeatable for admin' }
                                                                },
                                                                component: { class: 'SimpleInputComponent' },
                                                                constraints: { authorization: { allowRoles: ['Admin'] } },
                                                            }
                                                        }
                                                    },
                                                }
                                            ]
                                        }
                                    },
                                    layout: {
                                        class: 'RepeatableElementLayout',
                                        config: { hostCssClasses: 'row align-items-start' }
                                    },
                                    // requires mode view, so is kept
                                    constraints: { authorization: { allowRoles: [] }, allowModes: ['view'] }
                                }
                            },
                        },
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'Repeatable TextField with default wrapper defined',
                                helpText: 'Repeatable component help text',
                            }
                        },
                    },
                ]
            };
            const expected = {
                name: "remove-items-constrains-nested",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'repeatable_group_1',
                        model: {
                            class: 'RepeatableComponentModel',
                            config: { value: [{ text_1: "hello world from repeating groups" }] }
                        },
                        component: {
                            class: 'RepeatableComponent',
                            config: {
                                elementTemplate: {
                                    model: { class: 'GroupFieldModel', config: { value: {} } },
                                    component: {
                                        class: 'GroupFieldComponent',
                                        config: {
                                            wrapperCssClasses: 'col',
                                            componentDefinitions: [
                                                // <-- requires mode edit, so expect to be removed
                                                {
                                                    name: 'text_2',
                                                    model: { class: 'SimpleInputModel', config: { value: 'hello world 2!' } },
                                                    component: { class: 'SimpleInputComponent' },
                                                },
                                                // <-- requires role 'Admin', so is removed
                                            ]
                                        }
                                    },
                                    layout: {
                                        class: 'RepeatableElementLayoutComponent',
                                        config: { hostCssClasses: 'row align-items-start' }
                                    },
                                    // <-- requires mode view, so is kept, constraints removed
                                }
                            },
                        },
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'Repeatable TextField with default wrapper defined',
                                helpText: 'Repeatable component help text',
                            }
                        },
                    },
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = FormsService.buildClientFormConfig(formConfig);
            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);
            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
            done();
        });
    });
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRm9ybXNTZXJ2aWNlLnRlc3QuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi90eXBlc2NyaXB0L3Rlc3QvdW5pdC9zZXJ2aWNlcy9Gb3Jtc1NlcnZpY2UudGVzdC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOztBQUlBLElBQUksTUFBeUIsQ0FBQztBQUM5QixNQUFNLENBQUMsTUFBTSxDQUFDLENBQUMsSUFBSSxDQUFDLEdBQUcsQ0FBQyxFQUFFLENBQUMsTUFBTSxHQUFHLEdBQUcsQ0FBQyxNQUFNLENBQUMsQ0FBQztBQVFoRCxRQUFRLENBQUMsa0JBQWtCLEVBQUU7SUFDM0IsTUFBTSxDQUFDLFVBQVUsSUFBSTtRQUNuQixJQUFJLEVBQUUsQ0FBQztJQUNULENBQUMsQ0FBQyxDQUFDO0lBRUgsRUFBRSxDQUFDLHFDQUFxQyxFQUFFLFVBQVUsSUFBSTtRQUN0RCxJQUFJLEtBQUssR0FBRyxlQUFlLENBQUMsVUFBVSxFQUFFLENBQUM7UUFDekMsSUFBSSxVQUFVLEdBQUcsTUFBTSxDQUFDO1FBQ3hCLElBQUksUUFBUSxHQUFHLG1CQUFtQixDQUFDO1FBQ25DLFVBQVUsQ0FBQyxJQUFJLEVBQUUsQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLEVBQUU7WUFDN0IsS0FBSyxDQUFDLEdBQUcsQ0FBQyxPQUFPLENBQUMscUJBQXFCLEtBQUssQ0FBQyxFQUFFLElBQUksVUFBVSxFQUFFLENBQUMsQ0FBQztZQUNqRSxLQUFLLENBQUMsR0FBRyxDQUFDLE9BQU8sQ0FBQyxLQUFLLENBQUMsQ0FBQztRQUMzQixDQUFDLENBQUMsQ0FBQztRQUNILE9BQU8sQ0FBQyxHQUFHLENBQUMsV0FBVyxHQUFDLEtBQUssQ0FBQyxFQUFFLEdBQUMsY0FBYyxHQUFDLFVBQVUsQ0FBQyxDQUFDO1FBQzVELFlBQVksQ0FBQyw2QkFBNkIsQ0FBQyxLQUFLLEVBQUUsVUFBVSxFQUFFLElBQUksQ0FBQyxDQUFDLFNBQVMsQ0FBQyxVQUFTLElBQUk7WUFDekYsTUFBTSxDQUFDLElBQUksQ0FBQyxDQUFDLEVBQUUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxRQUFRLENBQUMsQ0FBQztZQUNoRCxJQUFJLEVBQUUsQ0FBQztRQUNULENBQUMsQ0FBQyxDQUFBO0lBQ0osQ0FBQyxDQUFDLENBQUM7SUFFSCxFQUFFLENBQUMsK0NBQStDLEVBQUUsVUFBVSxJQUFJO1FBRWhFLElBQUksUUFBUSxHQUFHLCtCQUErQixDQUFDO1FBRS9DLFlBQVksQ0FBQyxhQUFhLENBQUMsUUFBUSxFQUFFLElBQUksQ0FBQyxDQUFDLFNBQVMsQ0FBQyxVQUFTLElBQUk7WUFDaEUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsQ0FBQTtZQUNqQixNQUFNLENBQUMsSUFBSSxDQUFDLENBQUMsRUFBRSxDQUFDLElBQUksQ0FBQyxRQUFRLENBQUMsTUFBTSxFQUFFLFFBQVEsQ0FBQyxDQUFDO1lBQ2hELElBQUksRUFBRSxDQUFDO1FBQ1QsQ0FBQyxDQUFDLENBQUE7SUFDSixDQUFDLENBQUMsQ0FBQztJQUVILEVBQUUsQ0FBQyxnREFBZ0QsRUFBRSxVQUFVLElBQUk7UUFDakUsSUFBSSxLQUFLLEdBQUcsZUFBZSxDQUFDLFVBQVUsRUFBRSxDQUFDO1FBQ3pDLElBQUksUUFBUSxHQUFHLG1CQUFtQixDQUFDO1FBQ25DLElBQUksTUFBTSxHQUFHO1lBQ1gsWUFBWSxFQUFFO2dCQUNaLElBQUksRUFBRSxRQUFRO2dCQUNkLElBQUksRUFBRSxNQUFNO2FBQ2I7U0FDRixDQUFDO1FBQ0YsWUFBWSxDQUFDLE9BQU8sQ0FBQyxLQUFLLEVBQUUsRUFBRSxFQUFFLElBQUksRUFBRSxFQUFFLEVBQUUsTUFBTSxDQUFDLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxFQUFFO1lBQzVELE1BQU0sQ0FBQyxJQUFJLENBQUMsQ0FBQyxFQUFFLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FBQyxNQUFNLEVBQUUsUUFBUSxDQUFDLENBQUM7WUFDaEQsSUFBSSxFQUFFLENBQUM7UUFDVCxDQUFDLENBQUMsQ0FBQTtJQUNKLENBQUMsQ0FBQyxDQUFDO0lBRUgsRUFBRSxDQUFDLDhEQUE4RCxFQUFFLFVBQVUsSUFBSTtRQUMvRSxJQUFJLEtBQUssR0FBRyxlQUFlLENBQUMsVUFBVSxFQUFFLENBQUM7UUFDekMsSUFBSSxRQUFRLEdBQUcscUJBQXFCLENBQUM7UUFDckMsSUFBSSxNQUFNLEdBQUc7WUFDWCxZQUFZLEVBQUU7Z0JBQ1osSUFBSSxFQUFFLFFBQVE7Z0JBQ2QsSUFBSSxFQUFFLE1BQU07YUFDYjtZQUNELFFBQVEsRUFBRTtnQkFDUixFQUFFLEVBQUcsU0FBUztnQkFDZCxVQUFVLEVBQUcsT0FBTztnQkFDcEIsV0FBVyxFQUFHLE9BQU87Z0JBQ3JCLFdBQVcsRUFBRyxRQUFRO2dCQUN0QixTQUFTLEVBQUcsS0FBSztnQkFDakIsU0FBUyxFQUFHLElBQUk7Z0JBQ2hCLEtBQUssRUFBRyx1QkFBdUI7Z0JBQy9CLFNBQVMsRUFBRyxxQkFBcUI7Z0JBQ2pDLG9CQUFvQixFQUFHLEVBQUU7Z0JBQ3pCLElBQUksRUFBRyxDQUFDLE1BQU0sRUFBRSxNQUFNLEVBQUUsTUFBTSxDQUFDO2dCQUMvQixLQUFLLEVBQUcscUJBQXFCO2dCQUM3QixpQkFBaUIsRUFBRyxFQUFFO2dCQUN0QixzQkFBc0IsRUFBRyxFQUFFO2dCQUMzQixXQUFXLEVBQUcsRUFBRTtnQkFDaEIseUJBQXlCLEVBQUcsVUFBVTtnQkFDdEMsY0FBYyxFQUFHO29CQUNiLGNBQWMsRUFBRyxtQkFBbUI7b0JBQ3BDLEtBQUssRUFBRyx1QkFBdUI7b0JBQy9CLEtBQUssRUFBRyxxQ0FBcUM7aUJBQ2hEO2dCQUNELHdCQUF3QixFQUFHLENBQUM7d0JBQ3hCLGNBQWMsRUFBRyxpQkFBaUI7d0JBQ2xDLEtBQUssRUFBRyx1QkFBdUI7d0JBQy9CLEtBQUssRUFBRyxxQ0FBcUM7cUJBQ2hELENBQUM7YUFDSDtTQUNGLENBQUM7UUFFRixZQUFZLENBQUMsT0FBTyxDQUFDLEtBQUssRUFBRSxFQUFFLEVBQUUsSUFBSSxFQUFFLEVBQUUsRUFBRSxNQUFNLENBQUMsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEVBQUU7WUFDNUQsTUFBTSxDQUFDLElBQUksQ0FBQyxDQUFDLEVBQUUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxRQUFRLENBQUMsQ0FBQztZQUNoRCxJQUFJLEVBQUUsQ0FBQztRQUNULENBQUMsQ0FBQyxDQUFBO0lBQ0osQ0FBQyxDQUFDLENBQUM7SUFFSCxFQUFFLENBQUMsd0JBQXdCLEVBQUUsVUFBVSxJQUFJO1FBQ3pDLElBQUksS0FBSyxHQUFHLGVBQWUsQ0FBQyxVQUFVLEVBQUUsQ0FBQztRQUN6QyxJQUFJLFFBQVEsR0FBRyxtQkFBbUIsQ0FBQztRQUNuQyxZQUFZLENBQUMsT0FBTyxDQUFDLEtBQUssRUFBRSxRQUFRLEVBQUUsSUFBSSxFQUFFLE1BQU0sRUFBRSxFQUFFLENBQUMsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEVBQUU7WUFDbEUsTUFBTSxDQUFDLElBQUksQ0FBQyxDQUFDLEVBQUUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxRQUFRLENBQUMsQ0FBQztZQUNoRCxJQUFJLEVBQUUsQ0FBQztRQUNULENBQUMsQ0FBQyxDQUFBO0lBQ0osQ0FBQyxDQUFDLENBQUM7SUFFSCxFQUFFLENBQUMsc0NBQXNDLEVBQUUsVUFBVSxJQUFJO1FBQ3ZELElBQUksS0FBSyxHQUFHLGVBQWUsQ0FBQyxVQUFVLEVBQUUsQ0FBQztRQUN6QyxJQUFJLFFBQVEsR0FBRyxxQkFBcUIsQ0FBQztRQUNyQyxZQUFZLENBQUMsT0FBTyxDQUFDLEtBQUssRUFBRSxRQUFRLEVBQUUsSUFBSSxFQUFFLE1BQU0sRUFBRSxFQUFFLENBQUMsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEVBQUU7WUFDbEUsTUFBTSxDQUFDLElBQUksQ0FBQyxDQUFDLEVBQUUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxRQUFRLENBQUMsQ0FBQztZQUNoRCxJQUFJLEVBQUUsQ0FBQztRQUNULENBQUMsQ0FBQyxDQUFBO0lBQ0osQ0FBQyxDQUFDLENBQUM7SUFFRCxRQUFRLENBQUMsMEJBQTBCLEVBQUU7UUFFakMsRUFBRSxDQUFDLGtDQUFrQyxFQUFFLFVBQVUsSUFBSTtZQUNqRCxNQUFNLFVBQVUsR0FBb0I7Z0JBQ2hDLElBQUksRUFBRSxZQUFZO2dCQUNsQixJQUFJLEVBQUUsTUFBTTtnQkFDWixVQUFVLEVBQUUsSUFBSTtnQkFDaEIsY0FBYyxFQUFFLE1BQU07Z0JBQ3RCLHNCQUFzQixFQUFFO29CQUNwQiwwQkFBMEIsRUFBRSxLQUFLO2lCQUNwQztnQkFDRCxjQUFjLEVBQUUsa0JBQWtCO2dCQUNsQyxvQkFBb0IsRUFBRSxLQUFLO2dCQUMzQixvQkFBb0IsRUFBRTtvQkFDbEI7d0JBQ0ksSUFBSSxFQUFFLFFBQVE7d0JBQ2QsTUFBTSxFQUFFOzRCQUNKLEtBQUssRUFBRSxlQUFlOzRCQUN0QixNQUFNLEVBQUU7Z0NBQ0osS0FBSyxFQUFFLHdDQUF3QztnQ0FDL0MsUUFBUSxFQUFFLHFCQUFxQjs2QkFDbEM7eUJBQ0o7d0JBQ0QsS0FBSyxFQUFFOzRCQUNILEtBQUssRUFBRSxrQkFBa0I7NEJBQ3pCLE1BQU0sRUFBRTtnQ0FDSixZQUFZLEVBQUUsZ0JBQWdCOzZCQUNqQzt5QkFDSjt3QkFDRCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHNCQUFzQjt5QkFDaEM7d0JBQ0QsV0FBVyxFQUFFOzRCQUNULGFBQWEsRUFBRTtnQ0FDWCxVQUFVLEVBQUUsRUFBRTs2QkFDakI7NEJBQ0QsVUFBVSxFQUFFLEVBQUU7eUJBQ2pCO3FCQUNKO2lCQUNKO2FBQ0osQ0FBQztZQUNGLE1BQU0sUUFBUSxHQUFvQjtnQkFDOUIsSUFBSSxFQUFFLFlBQVk7Z0JBQ2xCLElBQUksRUFBRSxNQUFNO2dCQUNaLFVBQVUsRUFBRSxJQUFJO2dCQUNoQixjQUFjLEVBQUUsTUFBTTtnQkFDdEIsc0JBQXNCLEVBQUU7b0JBQ3BCLDBCQUEwQixFQUFFLEtBQUs7aUJBQ3BDO2dCQUNELGNBQWMsRUFBRSxrQkFBa0I7Z0JBQ2xDLG9CQUFvQixFQUFFLEtBQUs7Z0JBQzNCLG9CQUFvQixFQUFFO29CQUNsQjt3QkFDSSxJQUFJLEVBQUUsUUFBUTt3QkFDZCxNQUFNLEVBQUU7NEJBQ0osS0FBSyxFQUFFLGVBQWU7NEJBQ3RCLE1BQU0sRUFBRTtnQ0FDSixLQUFLLEVBQUUsd0NBQXdDO2dDQUMvQyxRQUFRLEVBQUUscUJBQXFCOzZCQUNsQzt5QkFDSjt3QkFDRCxLQUFLLEVBQUU7NEJBQ0gsS0FBSyxFQUFFLGtCQUFrQjs0QkFDekIsTUFBTSxFQUFFO2dDQUNKLEtBQUssRUFBRSxnQkFBZ0I7NkJBQzFCO3lCQUNKO3dCQUNELFNBQVMsRUFBRTs0QkFDUCxLQUFLLEVBQUUsc0JBQXNCO3lCQUNoQztxQkFDSjtpQkFDSjthQUNKLENBQUM7WUFDRixNQUFNLFFBQVEsR0FBRyxJQUFJLENBQUMsU0FBUyxDQUFDLFVBQVUsQ0FBQyxDQUFDO1lBQzVDLE1BQU0sTUFBTSxHQUFHLFlBQVksQ0FBQyxxQkFBcUIsQ0FBQyxVQUFVLENBQUMsQ0FBQztZQUU5RCw4Q0FBOEM7WUFDOUMsTUFBTSxDQUFDLElBQUksQ0FBQyxTQUFTLENBQUMsVUFBVSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsR0FBRyxDQUFDLFFBQVEsQ0FBQyxDQUFDO1lBRXBELG1EQUFtRDtZQUNuRCxNQUFNLENBQUMsTUFBTSxDQUFDLENBQUMsRUFBRSxDQUFDLEdBQUcsQ0FBQyxRQUFRLENBQUMsQ0FBQztZQUNoQyxJQUFJLEVBQUUsQ0FBQztRQUNYLENBQUMsQ0FBQyxDQUFDO1FBQ0gsRUFBRSxDQUFDLCtFQUErRSxFQUFFLFVBQVUsSUFBSTtZQUM5RixNQUFNLFVBQVUsR0FBb0I7Z0JBQ2hDLElBQUksRUFBRSw4QkFBOEI7Z0JBQ3BDLElBQUksRUFBRSxNQUFNO2dCQUNaLFVBQVUsRUFBRSxJQUFJO2dCQUNoQixjQUFjLEVBQUUsTUFBTTtnQkFDdEIsc0JBQXNCLEVBQUU7b0JBQ3BCLDBCQUEwQixFQUFFLEtBQUs7aUJBQ3BDO2dCQUNELGNBQWMsRUFBRSxrQkFBa0I7Z0JBQ2xDLG9CQUFvQixFQUFFLEtBQUs7Z0JBQzNCLG9CQUFvQixFQUFFO29CQUNsQjt3QkFDSSxJQUFJLEVBQUUsUUFBUTt3QkFDZCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHNCQUFzQjt5QkFDaEM7cUJBQ0o7b0JBQ0Q7d0JBQ0ksSUFBSSxFQUFFLFFBQVE7d0JBQ2QsTUFBTSxFQUFFOzRCQUNKLEtBQUssRUFBRSxlQUFlOzRCQUN0QixNQUFNLEVBQUU7Z0NBQ0osS0FBSyxFQUFFLHdDQUF3QztnQ0FDL0MsUUFBUSxFQUFFLHFCQUFxQjs2QkFDbEM7eUJBQ0o7d0JBQ0QsS0FBSyxFQUFFOzRCQUNILEtBQUssRUFBRSxrQkFBa0I7NEJBQ3pCLE1BQU0sRUFBRTtnQ0FDSixZQUFZLEVBQUUsZ0JBQWdCOzZCQUNqQzt5QkFDSjt3QkFDRCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHNCQUFzQjt5QkFDaEM7d0JBQ0QsV0FBVyxFQUFFOzRCQUNULGFBQWEsRUFBRTtnQ0FDWCxVQUFVLEVBQUUsQ0FBQyxPQUFPLEVBQUUsWUFBWSxDQUFDOzZCQUN0Qzs0QkFDRCxVQUFVLEVBQUUsRUFBRTt5QkFDakI7cUJBQ0o7aUJBQ0o7YUFDSixDQUFDO1lBQUEsTUFBTSxRQUFRLEdBQUc7Z0JBQ2YsSUFBSSxFQUFFLDhCQUE4QjtnQkFDcEMsSUFBSSxFQUFFLE1BQU07Z0JBQ1osVUFBVSxFQUFFLElBQUk7Z0JBQ2hCLGNBQWMsRUFBRSxNQUFNO2dCQUN0QixzQkFBc0IsRUFBRTtvQkFDcEIsMEJBQTBCLEVBQUUsS0FBSztpQkFDcEM7Z0JBQ0QsY0FBYyxFQUFFLGtCQUFrQjtnQkFDbEMsb0JBQW9CLEVBQUUsS0FBSztnQkFDM0Isb0JBQW9CLEVBQUU7b0JBQ2xCO3dCQUNJLElBQUksRUFBRSxRQUFRO3dCQUNkLFNBQVMsRUFBRTs0QkFDUCxLQUFLLEVBQUUsc0JBQXNCO3lCQUNoQztxQkFDSjtpQkFDSjthQUNKLENBQUM7WUFDRixNQUFNLFFBQVEsR0FBRyxJQUFJLENBQUMsU0FBUyxDQUFDLFVBQVUsQ0FBQyxDQUFDO1lBQzVDLE1BQU0sTUFBTSxHQUFHLFlBQVksQ0FBQyxxQkFBcUIsQ0FBQyxVQUFVLENBQUMsQ0FBQztZQUU5RCw4Q0FBOEM7WUFDOUMsTUFBTSxDQUFDLElBQUksQ0FBQyxTQUFTLENBQUMsVUFBVSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsR0FBRyxDQUFDLFFBQVEsQ0FBQyxDQUFDO1lBRXBELG1EQUFtRDtZQUNuRCxNQUFNLENBQUMsTUFBTSxDQUFDLENBQUMsRUFBRSxDQUFDLEdBQUcsQ0FBQyxRQUFRLENBQUMsQ0FBQztZQUNoQyxJQUFJLEVBQUUsQ0FBQztRQUNYLENBQUMsQ0FBQyxDQUFDO1FBQ0gsRUFBRSxDQUFDLGdGQUFnRixFQUFFLFVBQVUsSUFBSTtZQUMvRixNQUFNLFVBQVUsR0FBb0I7Z0JBQ2hDLElBQUksRUFBRSw2QkFBNkI7Z0JBQ25DLElBQUksRUFBRSxNQUFNO2dCQUNaLFVBQVUsRUFBRSxJQUFJO2dCQUNoQixjQUFjLEVBQUUsTUFBTTtnQkFDdEIsc0JBQXNCLEVBQUU7b0JBQ3BCLDBCQUEwQixFQUFFLEtBQUs7aUJBQ3BDO2dCQUNELGNBQWMsRUFBRSxrQkFBa0I7Z0JBQ2xDLG9CQUFvQixFQUFFLEtBQUs7Z0JBQzNCLG9CQUFvQixFQUFFO29CQUNsQjt3QkFDSSxJQUFJLEVBQUUsUUFBUTt3QkFDZCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHNCQUFzQjt5QkFDaEM7cUJBQ0o7b0JBQ0Q7d0JBQ0ksSUFBSSxFQUFFLFFBQVE7d0JBQ2QsTUFBTSxFQUFFOzRCQUNKLEtBQUssRUFBRSxlQUFlOzRCQUN0QixNQUFNLEVBQUU7Z0NBQ0osS0FBSyxFQUFFLHdDQUF3QztnQ0FDL0MsUUFBUSxFQUFFLHFCQUFxQjs2QkFDbEM7eUJBQ0o7d0JBQ0QsS0FBSyxFQUFFOzRCQUNILEtBQUssRUFBRSxrQkFBa0I7NEJBQ3pCLE1BQU0sRUFBRTtnQ0FDSixZQUFZLEVBQUUsZ0JBQWdCOzZCQUNqQzt5QkFDSjt3QkFDRCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHNCQUFzQjt5QkFDaEM7d0JBQ0QsV0FBVyxFQUFFOzRCQUNULGFBQWEsRUFBRTtnQ0FDWCxRQUFRLEVBQUUsdUNBQXVDOzZCQUNwRDt5QkFDSjt3QkFDRCxXQUFXLEVBQUU7NEJBQ1QsYUFBYSxFQUFFO2dDQUNYLFVBQVUsRUFBRSxFQUFFOzZCQUNqQjs0QkFDRCxVQUFVLEVBQUUsQ0FBQyxNQUFNLENBQUM7eUJBQ3ZCO3FCQUNKO2lCQUNKO2FBQ0osQ0FBQztZQUNGLE1BQU0sUUFBUSxHQUFHO2dCQUNiLElBQUksRUFBRSw2QkFBNkI7Z0JBQ25DLElBQUksRUFBRSxNQUFNO2dCQUNaLFVBQVUsRUFBRSxJQUFJO2dCQUNoQixjQUFjLEVBQUUsTUFBTTtnQkFDdEIsc0JBQXNCLEVBQUU7b0JBQ3BCLDBCQUEwQixFQUFFLEtBQUs7aUJBQ3BDO2dCQUNELGNBQWMsRUFBRSxrQkFBa0I7Z0JBQ2xDLG9CQUFvQixFQUFFLEtBQUs7Z0JBQzNCLG9CQUFvQixFQUFFO29CQUNsQjt3QkFDSSxJQUFJLEVBQUUsUUFBUTt3QkFDZCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHNCQUFzQjt5QkFDaEM7cUJBQ0o7aUJBRUo7YUFDSixDQUFDO1lBQ0YsTUFBTSxRQUFRLEdBQUcsSUFBSSxDQUFDLFNBQVMsQ0FBQyxVQUFVLENBQUMsQ0FBQztZQUM1QyxNQUFNLE1BQU0sR0FBRyxZQUFZLENBQUMscUJBQXFCLENBQUMsVUFBVSxDQUFDLENBQUM7WUFFOUQsOENBQThDO1lBQzlDLE1BQU0sQ0FBQyxJQUFJLENBQUMsU0FBUyxDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLEdBQUcsQ0FBQyxRQUFRLENBQUMsQ0FBQztZQUVwRCxtREFBbUQ7WUFDbkQsTUFBTSxDQUFDLE1BQU0sQ0FBQyxDQUFDLEVBQUUsQ0FBQyxHQUFHLENBQUMsUUFBUSxDQUFDLENBQUM7WUFDaEMsSUFBSSxFQUFFLENBQUM7UUFDWCxDQUFDLENBQUMsQ0FBQztRQUNILEVBQUUsQ0FBQyx5R0FBeUcsRUFBRSxVQUFVLElBQUk7WUFDeEgsTUFBTSxVQUFVLEdBQW9CO2dCQUNoQyxJQUFJLEVBQUUsZ0NBQWdDO2dCQUN0QyxJQUFJLEVBQUUsTUFBTTtnQkFDWixVQUFVLEVBQUUsSUFBSTtnQkFDaEIsY0FBYyxFQUFFLE1BQU07Z0JBQ3RCLHNCQUFzQixFQUFFO29CQUNwQiwwQkFBMEIsRUFBRSxLQUFLO2lCQUNwQztnQkFDRCxjQUFjLEVBQUUsa0JBQWtCO2dCQUNsQyxvQkFBb0IsRUFBRSxLQUFLO2dCQUMzQixvQkFBb0IsRUFBRTtvQkFDbEI7d0JBQ0ksSUFBSSxFQUFFLG9CQUFvQjt3QkFDMUIsS0FBSyxFQUFFOzRCQUNILEtBQUssRUFBRSxpQkFBaUI7NEJBQ3hCLE1BQU0sRUFBRSxFQUFDLFlBQVksRUFBRSxDQUFDLEVBQUMsTUFBTSxFQUFFLG1DQUFtQyxFQUFDLENBQUMsRUFBQzt5QkFDMUU7d0JBQ0QsU0FBUyxFQUFFOzRCQUNQLEtBQUssRUFBRSxxQkFBcUI7NEJBQzVCLE1BQU0sRUFBRTtnQ0FDSixlQUFlLEVBQUU7b0NBQ2IsSUFBSSxFQUFFLElBQUk7b0NBQ1YsS0FBSyxFQUFFLEVBQUMsS0FBSyxFQUFFLFlBQVksRUFBRSxNQUFNLEVBQUUsRUFBQyxZQUFZLEVBQUUsRUFBRSxFQUFDLEVBQUM7b0NBQ3hELFNBQVMsRUFBRTt3Q0FDUCxLQUFLLEVBQUUsZ0JBQWdCO3dDQUN2QixNQUFNLEVBQUU7NENBQ0osaUJBQWlCLEVBQUUsS0FBSzs0Q0FDeEIsb0JBQW9CLEVBQUU7Z0RBQ2xCO29EQUNJLDhDQUE4QztvREFDOUMsSUFBSSxFQUFFLFFBQVE7b0RBQ2QsS0FBSyxFQUFFO3dEQUNILEtBQUssRUFBRSxrQkFBa0I7d0RBQ3pCLE1BQU0sRUFBRSxFQUFDLFlBQVksRUFBRSxnQkFBZ0IsR0FBRTtxREFDNUM7b0RBQ0QsU0FBUyxFQUFFLEVBQUMsS0FBSyxFQUFFLHNCQUFzQixFQUFDO29EQUMxQyxXQUFXLEVBQUUsRUFBQyxVQUFVLEVBQUUsQ0FBQyxNQUFNLENBQUMsRUFBQztpREFDdEM7Z0RBQ0Q7b0RBQ0ksSUFBSSxFQUFFLFFBQVE7b0RBQ2QsS0FBSyxFQUFFLEVBQUMsS0FBSyxFQUFFLGtCQUFrQixFQUFFLE1BQU0sRUFBRSxFQUFDLFlBQVksRUFBRSxnQkFBZ0IsRUFBQyxFQUFDO29EQUM1RSxTQUFTLEVBQUUsRUFBQyxLQUFLLEVBQUUsc0JBQXNCLEVBQUM7aURBQzdDO2dEQUNEO29EQUNJLHVDQUF1QztvREFDdkMsSUFBSSxFQUFFLHNCQUFzQjtvREFDNUIsS0FBSyxFQUFFLEVBQUMsS0FBSyxFQUFFLGlCQUFpQixFQUFFLE1BQU0sRUFBQyxFQUFFLEVBQUM7b0RBQzVDLFNBQVMsRUFBRTt3REFDUCxLQUFLLEVBQUUscUJBQXFCO3dEQUM1QixNQUFNLEVBQUU7NERBQ0osZUFBZSxFQUFFO2dFQUNiLElBQUksRUFBRSxJQUFJO2dFQUNWLEtBQUssRUFBRTtvRUFDSCxLQUFLLEVBQUUsa0JBQWtCO29FQUN6QixNQUFNLEVBQUUsRUFBQyxZQUFZLEVBQUUsdUNBQXVDLEVBQUM7aUVBQ2xFO2dFQUNELFNBQVMsRUFBRSxFQUFDLEtBQUssRUFBRSxzQkFBc0IsRUFBQztnRUFDMUMsV0FBVyxFQUFFLEVBQUMsYUFBYSxFQUFFLEVBQUMsVUFBVSxFQUFFLENBQUMsT0FBTyxDQUFDLEVBQUMsRUFBQzs2REFDeEQ7eURBQ0o7cURBQ0o7aURBQ0o7NkNBQ0o7eUNBQ0o7cUNBQ0o7b0NBQ0QsTUFBTSxFQUFFO3dDQUNKLEtBQUssRUFBRSx5QkFBeUI7d0NBQ2hDLE1BQU0sRUFBRSxFQUFDLGNBQWMsRUFBRSx1QkFBdUIsRUFBQztxQ0FDcEQ7b0NBQ0QsaUNBQWlDO29DQUNqQyxXQUFXLEVBQUUsRUFBQyxhQUFhLEVBQUUsRUFBQyxVQUFVLEVBQUUsRUFBRSxFQUFDLEVBQUUsVUFBVSxFQUFFLENBQUMsTUFBTSxDQUFDLEVBQUM7aUNBQ3ZFOzZCQUNKO3lCQUNKO3dCQUNELE1BQU0sRUFBRTs0QkFDSixLQUFLLEVBQUUsZUFBZTs0QkFDdEIsTUFBTSxFQUFFO2dDQUNKLEtBQUssRUFBRSxtREFBbUQ7Z0NBQzFELFFBQVEsRUFBRSxnQ0FBZ0M7NkJBQzdDO3lCQUNKO3FCQUNKO2lCQUNKO2FBQ0osQ0FBQztZQUNGLE1BQU0sUUFBUSxHQUFHO2dCQUNiLElBQUksRUFBRSxnQ0FBZ0M7Z0JBQ3RDLElBQUksRUFBRSxNQUFNO2dCQUNaLFVBQVUsRUFBRSxJQUFJO2dCQUNoQixjQUFjLEVBQUUsTUFBTTtnQkFDdEIsc0JBQXNCLEVBQUU7b0JBQ3BCLDBCQUEwQixFQUFFLEtBQUs7aUJBQ3BDO2dCQUNELGNBQWMsRUFBRSxrQkFBa0I7Z0JBQ2xDLG9CQUFvQixFQUFFLEtBQUs7Z0JBQzNCLG9CQUFvQixFQUFFO29CQUNsQjt3QkFDSSxJQUFJLEVBQUUsb0JBQW9CO3dCQUMxQixLQUFLLEVBQUU7NEJBQ0gsS0FBSyxFQUFFLDBCQUEwQjs0QkFDakMsTUFBTSxFQUFFLEVBQUMsS0FBSyxFQUFFLENBQUMsRUFBQyxNQUFNLEVBQUUsbUNBQW1DLEVBQUMsQ0FBQyxFQUFDO3lCQUNuRTt3QkFDRCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHFCQUFxQjs0QkFDNUIsTUFBTSxFQUFFO2dDQUNKLGVBQWUsRUFBRTtvQ0FDYixLQUFLLEVBQUUsRUFBQyxLQUFLLEVBQUUsaUJBQWlCLEVBQUUsTUFBTSxFQUFFLEVBQUMsS0FBSyxFQUFFLEVBQUUsRUFBQyxFQUFDO29DQUN0RCxTQUFTLEVBQUU7d0NBQ1AsS0FBSyxFQUFFLHFCQUFxQjt3Q0FDNUIsTUFBTSxFQUFFOzRDQUNKLGlCQUFpQixFQUFFLEtBQUs7NENBQ3hCLG9CQUFvQixFQUFFO2dEQUNsQixrREFBa0Q7Z0RBQ2xEO29EQUNJLElBQUksRUFBRSxRQUFRO29EQUNkLEtBQUssRUFBRSxFQUFDLEtBQUssRUFBRSxrQkFBa0IsRUFBRSxNQUFNLEVBQUUsRUFBQyxLQUFLLEVBQUUsZ0JBQWdCLEVBQUMsRUFBQztvREFDckUsU0FBUyxFQUFFLEVBQUMsS0FBSyxFQUFFLHNCQUFzQixFQUFDO2lEQUM3QztnREFDRCwyQ0FBMkM7NkNBQzlDO3lDQUNKO3FDQUNKO29DQUNELE1BQU0sRUFBRTt3Q0FDSixLQUFLLEVBQUUsa0NBQWtDO3dDQUN6QyxNQUFNLEVBQUUsRUFBQyxjQUFjLEVBQUUsdUJBQXVCLEVBQUM7cUNBQ3BEO29DQUNELDBEQUEwRDtpQ0FDN0Q7NkJBQ0o7eUJBQ0o7d0JBQ0QsTUFBTSxFQUFFOzRCQUNKLEtBQUssRUFBRSxlQUFlOzRCQUN0QixNQUFNLEVBQUU7Z0NBQ0osS0FBSyxFQUFFLG1EQUFtRDtnQ0FDMUQsUUFBUSxFQUFFLGdDQUFnQzs2QkFDN0M7eUJBQ0o7cUJBQ0o7aUJBQ0o7YUFDSixDQUFDO1lBQ0YsTUFBTSxRQUFRLEdBQUcsSUFBSSxDQUFDLFNBQVMsQ0FBQyxVQUFVLENBQUMsQ0FBQztZQUM1QyxNQUFNLE1BQU0sR0FBRyxZQUFZLENBQUMscUJBQXFCLENBQUMsVUFBVSxDQUFDLENBQUM7WUFFOUQsOENBQThDO1lBQzlDLE1BQU0sQ0FBQyxJQUFJLENBQUMsU0FBUyxDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLEdBQUcsQ0FBQyxRQUFRLENBQUMsQ0FBQztZQUVwRCxtREFBbUQ7WUFDbkQsTUFBTSxDQUFDLE1BQU0sQ0FBQyxDQUFDLEVBQUUsQ0FBQyxHQUFHLENBQUMsUUFBUSxDQUFDLENBQUM7WUFDaEMsSUFBSSxFQUFFLENBQUM7UUFDWCxDQUFDLENBQUMsQ0FBQztJQUNQLENBQUMsQ0FBQyxDQUFDO0FBQ1AsQ0FBQyxDQUFDLENBQUMifQ==