"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let expect;
import("chai").then(mod => expect = mod.expect);
describe('The FormsService', function () {
    before(function (done) {
        done();
    });
    it('should return the default RDMP form', function (done) {
        var brand = BrandingService.getDefault();
        var recordType = 'rdmp';
        var formName = 'default-1.0-draft';
        RecordType.find().then(forms => {
            sails.log.verbose(`going to look for ${brand.id}_${recordType}`);
            sails.log.verbose(forms);
        });
        console.log('brand.id ' + brand.id + ' recordType ' + recordType);
        FormsService.getFormByStartingWorkflowStep(brand, recordType, true).subscribe(function (form) {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should get dataPublication-1.0-embargoed form', function (done) {
        var formName = 'dataPublication-1.0-embargoed';
        FormsService.getFormByName(formName, true).subscribe(function (form) {
            console.log(form);
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should return the form based of a given record', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'default-1.0-draft';
        let record = {
            metaMetadata: {
                form: formName,
                type: 'rdmp'
            }
        };
        FormsService.getForm(brand, '', true, '', record).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should return the autogenerated form based of a given record', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'generated-view-only';
        let record = {
            metaMetadata: {
                form: formName,
                type: 'rdmp'
            },
            metadata: {
                ID: 's823456',
                GIVEN_NAME: 'Ant10',
                OTHER_NAMES: 'Other',
                FAMILY_NAME: 'Season',
                PREF_NAME: 'Ant',
                HONORIFIC: 'Sr',
                EMAIL: 'notAReal@email.edu.au',
                JOB_TITLE: 'Assistant Professor',
                NLA_PARTY_IDENTIFIER: '',
                URIs: ['URI1', 'URI2', 'URI3'],
                ORCID: '0000-0001-7269-2286',
                PERSONAL_HOMEPAGE: '',
                STAFF_PROFILE_HOMEPAGE: '',
                DESCRIPTION: '',
                RESEARCH_ELEMENTS_USER_ID: '12345678',
                contributor_ci: {
                    text_full_name: 'Prof Ant10 Season',
                    email: 'notAReal@email.edu.au',
                    orcid: 'http://orcid.org/0000-0000-0000-000'
                },
                contributor_data_manager: [{
                        text_full_name: 'Prof Ant Season',
                        email: 'notAReal@email.edu.au',
                        orcid: 'http://orcid.org/0000-0000-0000-000'
                    }]
            }
        };
        FormsService.getForm(brand, '', true, '', record).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should return the form', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'default-1.0-draft';
        FormsService.getForm(brand, formName, true, 'rdmp', {}).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    it('should return the autogenerated form', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'generated-view-only';
        FormsService.getForm(brand, formName, true, 'rdmp', {}).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        });
    });
    describe("build client form config", function () {
        it('should build the expected config', function (done) {
            const formConfig = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        constraints: {
                            authorization: {
                                allowRoles: [],
                            },
                            allowModes: [],
                        },
                    }
                ]
            };
            const expected = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                validators: [],
                componentDefinitions: [
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                                autofocus: false,
                                cssClassesMap: {},
                                disabled: false,
                                editMode: true,
                                helpTextVisible: false,
                                helpTextVisibleOnInit: false,
                                labelRequiredStr: "*",
                                readonly: false,
                                visible: true,
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                value: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                            config: {
                                autofocus: false,
                                disabled: false,
                                editMode: true,
                                readonly: false,
                                type: "text",
                                visible: true,
                            },
                        },
                    }
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = FormsService.buildClientFormConfig(formConfig);
            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);
            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
            done();
        });
        it('should remove the component because the user does not have the required roles', function (done) {
            const formConfig = {
                name: "remove-item-constraint-roles",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                        },
                    },
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        constraints: {
                            authorization: {
                                allowRoles: ['Admin', 'Librarians'],
                            },
                            allowModes: [],
                        },
                    }
                ]
            };
            const expected = {
                name: "remove-item-constraint-roles",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                validators: [],
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                            config: {
                                autofocus: false,
                                disabled: false,
                                editMode: true,
                                readonly: false,
                                type: "text",
                                visible: true,
                            },
                        },
                    }
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = FormsService.buildClientFormConfig(formConfig);
            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);
            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
            done();
        });
        it('should remove the component because the client does not have the required mode', function (done) {
            const formConfig = {
                name: "remove-item-constraint-mode",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                        },
                    },
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        expressions: {
                            'model.value': {
                                template: `<%= _.get(model,'text_1_event','') %>`
                            }
                        },
                        constraints: {
                            authorization: {
                                allowRoles: [],
                            },
                            allowModes: ['edit'],
                        },
                    }
                ]
            };
            const expected = {
                name: "remove-item-constraint-mode",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                validators: [],
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                            config: {
                                autofocus: false,
                                disabled: false,
                                editMode: true,
                                readonly: false,
                                type: "text",
                                visible: true,
                            },
                        },
                    },
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = FormsService.buildClientFormConfig(formConfig);
            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);
            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
            done();
        });
        it('should remove the components nested in repeatable and group components when the constraints are not met', function (done) {
            const formConfig = {
                name: "remove-items-constrains-nested",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                componentDefinitions: [
                    {
                        name: 'repeatable_group_1',
                        model: {
                            class: 'RepeatableModel',
                            config: { defaultValue: [{ text_1: "hello world from repeating groups" }] }
                        },
                        component: {
                            class: 'RepeatableComponent',
                            config: {
                                elementTemplate: {
                                    name: "",
                                    model: { class: 'GroupModel', config: { defaultValue: {} } },
                                    component: {
                                        class: 'GroupComponent',
                                        config: {
                                            wrapperCssClasses: 'col',
                                            componentDefinitions: [
                                                {
                                                    // requires mode edit, so expect to be removed
                                                    name: 'text_1',
                                                    model: {
                                                        class: 'SimpleInputModel',
                                                        config: { defaultValue: 'hello world 1!', }
                                                    },
                                                    component: { class: 'SimpleInputComponent' },
                                                    constraints: { allowModes: ['edit'] },
                                                },
                                                {
                                                    name: 'text_2',
                                                    model: {
                                                        class: 'SimpleInputModel',
                                                        config: { defaultValue: 'hello world 2!' }
                                                    },
                                                    component: { class: 'SimpleInputComponent' },
                                                },
                                                {
                                                    // requires role 'Admin', so is removed
                                                    name: 'repeatable_for_admin',
                                                    model: { class: 'RepeatableModel', config: {} },
                                                    component: {
                                                        class: 'RepeatableComponent',
                                                        config: {
                                                            elementTemplate: {
                                                                name: null,
                                                                model: {
                                                                    class: 'SimpleInputModel',
                                                                    config: { defaultValue: 'hello world from repeatable for admin' }
                                                                },
                                                                component: { class: 'SimpleInputComponent' },
                                                                constraints: { authorization: { allowRoles: ['Admin'] } },
                                                            }
                                                        }
                                                    },
                                                }
                                            ]
                                        }
                                    },
                                    layout: {
                                        class: 'RepeatableElementLayout',
                                        config: { hostCssClasses: 'row align-items-start' }
                                    },
                                    // requires mode view, so is kept
                                    constraints: { authorization: { allowRoles: [] }, allowModes: ['view'] }
                                }
                            },
                        },
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'Repeatable TextField with default wrapper defined',
                                helpText: 'Repeatable component help text',
                            }
                        },
                    },
                ]
            };
            const expected = {
                name: "remove-items-constrains-nested",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                skipValidationOnSave: false,
                validators: [],
                componentDefinitions: [
                    {
                        name: 'repeatable_group_1',
                        model: {
                            class: 'RepeatableModel',
                            config: { value: [{ text_1: "hello world from repeating groups" }] }
                        },
                        component: {
                            class: 'RepeatableComponent',
                            config: {
                                autofocus: false,
                                disabled: false,
                                editMode: true,
                                readonly: false,
                                visible: true,
                                elementTemplate: {
                                    name: "",
                                    model: { class: 'GroupModel', config: {} },
                                    component: {
                                        class: 'GroupComponent',
                                        config: {
                                            autofocus: false,
                                            disabled: false,
                                            editMode: true,
                                            readonly: false,
                                            visible: true,
                                            wrapperCssClasses: 'col',
                                            componentDefinitions: [
                                                // <-- requires mode edit, so expect to be removed
                                                {
                                                    name: 'text_2',
                                                    model: {
                                                        class: 'SimpleInputModel',
                                                        config: {}
                                                    },
                                                    component: {
                                                        class: 'SimpleInputComponent',
                                                        config: {
                                                            autofocus: false,
                                                            disabled: false,
                                                            editMode: true,
                                                            readonly: false,
                                                            type: "text",
                                                            visible: true,
                                                        },
                                                    },
                                                },
                                                // <-- requires role 'Admin', so is removed
                                            ]
                                        }
                                    },
                                    layout: {
                                        class: 'RepeatableElementLayout',
                                        config: {
                                            hostCssClasses: 'row align-items-start',
                                            autofocus: false,
                                            cssClassesMap: {},
                                            disabled: false,
                                            editMode: true,
                                            helpTextVisible: false,
                                            helpTextVisibleOnInit: false,
                                            labelRequiredStr: "*",
                                            readonly: false,
                                            visible: true,
                                        }
                                    },
                                    // <-- requires mode view, so is kept, constraints removed
                                }
                            },
                        },
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'Repeatable TextField with default wrapper defined',
                                helpText: 'Repeatable component help text',
                                autofocus: false,
                                cssClassesMap: {},
                                disabled: false,
                                editMode: true,
                                helpTextVisible: false,
                                helpTextVisibleOnInit: false,
                                labelRequiredStr: "*",
                                readonly: false,
                                visible: true,
                            }
                        },
                    },
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = FormsService.buildClientFormConfig(formConfig);
            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);
            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
            done();
        });
    });
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRm9ybXNTZXJ2aWNlLnRlc3QuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi90eXBlc2NyaXB0L3Rlc3QvdW5pdC9zZXJ2aWNlcy9Gb3Jtc1NlcnZpY2UudGVzdC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOztBQUlBLElBQUksTUFBeUIsQ0FBQztBQUM5QixNQUFNLENBQUMsTUFBTSxDQUFDLENBQUMsSUFBSSxDQUFDLEdBQUcsQ0FBQyxFQUFFLENBQUMsTUFBTSxHQUFHLEdBQUcsQ0FBQyxNQUFNLENBQUMsQ0FBQztBQVFoRCxRQUFRLENBQUMsa0JBQWtCLEVBQUU7SUFDekIsTUFBTSxDQUFDLFVBQVUsSUFBSTtRQUNqQixJQUFJLEVBQUUsQ0FBQztJQUNYLENBQUMsQ0FBQyxDQUFDO0lBRUgsRUFBRSxDQUFDLHFDQUFxQyxFQUFFLFVBQVUsSUFBSTtRQUNwRCxJQUFJLEtBQUssR0FBRyxlQUFlLENBQUMsVUFBVSxFQUFFLENBQUM7UUFDekMsSUFBSSxVQUFVLEdBQUcsTUFBTSxDQUFDO1FBQ3hCLElBQUksUUFBUSxHQUFHLG1CQUFtQixDQUFDO1FBQ25DLFVBQVUsQ0FBQyxJQUFJLEVBQUUsQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLEVBQUU7WUFDM0IsS0FBSyxDQUFDLEdBQUcsQ0FBQyxPQUFPLENBQUMscUJBQXFCLEtBQUssQ0FBQyxFQUFFLElBQUksVUFBVSxFQUFFLENBQUMsQ0FBQztZQUNqRSxLQUFLLENBQUMsR0FBRyxDQUFDLE9BQU8sQ0FBQyxLQUFLLENBQUMsQ0FBQztRQUM3QixDQUFDLENBQUMsQ0FBQztRQUNILE9BQU8sQ0FBQyxHQUFHLENBQUMsV0FBVyxHQUFHLEtBQUssQ0FBQyxFQUFFLEdBQUcsY0FBYyxHQUFHLFVBQVUsQ0FBQyxDQUFDO1FBQ2xFLFlBQVksQ0FBQyw2QkFBNkIsQ0FBQyxLQUFLLEVBQUUsVUFBVSxFQUFFLElBQUksQ0FBQyxDQUFDLFNBQVMsQ0FBQyxVQUFVLElBQUk7WUFDeEYsTUFBTSxDQUFDLElBQUksQ0FBQyxDQUFDLEVBQUUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxRQUFRLENBQUMsQ0FBQztZQUNoRCxJQUFJLEVBQUUsQ0FBQztRQUNYLENBQUMsQ0FBQyxDQUFBO0lBQ04sQ0FBQyxDQUFDLENBQUM7SUFFSCxFQUFFLENBQUMsK0NBQStDLEVBQUUsVUFBVSxJQUFJO1FBRTlELElBQUksUUFBUSxHQUFHLCtCQUErQixDQUFDO1FBRS9DLFlBQVksQ0FBQyxhQUFhLENBQUMsUUFBUSxFQUFFLElBQUksQ0FBQyxDQUFDLFNBQVMsQ0FBQyxVQUFVLElBQUk7WUFDL0QsT0FBTyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsQ0FBQTtZQUNqQixNQUFNLENBQUMsSUFBSSxDQUFDLENBQUMsRUFBRSxDQUFDLElBQUksQ0FBQyxRQUFRLENBQUMsTUFBTSxFQUFFLFFBQVEsQ0FBQyxDQUFDO1lBQ2hELElBQUksRUFBRSxDQUFDO1FBQ1gsQ0FBQyxDQUFDLENBQUE7SUFDTixDQUFDLENBQUMsQ0FBQztJQUVILEVBQUUsQ0FBQyxnREFBZ0QsRUFBRSxVQUFVLElBQUk7UUFDL0QsSUFBSSxLQUFLLEdBQUcsZUFBZSxDQUFDLFVBQVUsRUFBRSxDQUFDO1FBQ3pDLElBQUksUUFBUSxHQUFHLG1CQUFtQixDQUFDO1FBQ25DLElBQUksTUFBTSxHQUFHO1lBQ1QsWUFBWSxFQUFFO2dCQUNWLElBQUksRUFBRSxRQUFRO2dCQUNkLElBQUksRUFBRSxNQUFNO2FBQ2Y7U0FDSixDQUFDO1FBQ0YsWUFBWSxDQUFDLE9BQU8sQ0FBQyxLQUFLLEVBQUUsRUFBRSxFQUFFLElBQUksRUFBRSxFQUFFLEVBQUUsTUFBTSxDQUFDLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxFQUFFO1lBQzFELE1BQU0sQ0FBQyxJQUFJLENBQUMsQ0FBQyxFQUFFLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FBQyxNQUFNLEVBQUUsUUFBUSxDQUFDLENBQUM7WUFDaEQsSUFBSSxFQUFFLENBQUM7UUFDWCxDQUFDLENBQUMsQ0FBQTtJQUNOLENBQUMsQ0FBQyxDQUFDO0lBRUgsRUFBRSxDQUFDLDhEQUE4RCxFQUFFLFVBQVUsSUFBSTtRQUM3RSxJQUFJLEtBQUssR0FBRyxlQUFlLENBQUMsVUFBVSxFQUFFLENBQUM7UUFDekMsSUFBSSxRQUFRLEdBQUcscUJBQXFCLENBQUM7UUFDckMsSUFBSSxNQUFNLEdBQUc7WUFDVCxZQUFZLEVBQUU7Z0JBQ1YsSUFBSSxFQUFFLFFBQVE7Z0JBQ2QsSUFBSSxFQUFFLE1BQU07YUFDZjtZQUNELFFBQVEsRUFBRTtnQkFDTixFQUFFLEVBQUUsU0FBUztnQkFDYixVQUFVLEVBQUUsT0FBTztnQkFDbkIsV0FBVyxFQUFFLE9BQU87Z0JBQ3BCLFdBQVcsRUFBRSxRQUFRO2dCQUNyQixTQUFTLEVBQUUsS0FBSztnQkFDaEIsU0FBUyxFQUFFLElBQUk7Z0JBQ2YsS0FBSyxFQUFFLHVCQUF1QjtnQkFDOUIsU0FBUyxFQUFFLHFCQUFxQjtnQkFDaEMsb0JBQW9CLEVBQUUsRUFBRTtnQkFDeEIsSUFBSSxFQUFFLENBQUMsTUFBTSxFQUFFLE1BQU0sRUFBRSxNQUFNLENBQUM7Z0JBQzlCLEtBQUssRUFBRSxxQkFBcUI7Z0JBQzVCLGlCQUFpQixFQUFFLEVBQUU7Z0JBQ3JCLHNCQUFzQixFQUFFLEVBQUU7Z0JBQzFCLFdBQVcsRUFBRSxFQUFFO2dCQUNmLHlCQUF5QixFQUFFLFVBQVU7Z0JBQ3JDLGNBQWMsRUFBRTtvQkFDWixjQUFjLEVBQUUsbUJBQW1CO29CQUNuQyxLQUFLLEVBQUUsdUJBQXVCO29CQUM5QixLQUFLLEVBQUUscUNBQXFDO2lCQUMvQztnQkFDRCx3QkFBd0IsRUFBRSxDQUFDO3dCQUN2QixjQUFjLEVBQUUsaUJBQWlCO3dCQUNqQyxLQUFLLEVBQUUsdUJBQXVCO3dCQUM5QixLQUFLLEVBQUUscUNBQXFDO3FCQUMvQyxDQUFDO2FBQ0w7U0FDSixDQUFDO1FBRUYsWUFBWSxDQUFDLE9BQU8sQ0FBQyxLQUFLLEVBQUUsRUFBRSxFQUFFLElBQUksRUFBRSxFQUFFLEVBQUUsTUFBTSxDQUFDLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxFQUFFO1lBQzFELE1BQU0sQ0FBQyxJQUFJLENBQUMsQ0FBQyxFQUFFLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FBQyxNQUFNLEVBQUUsUUFBUSxDQUFDLENBQUM7WUFDaEQsSUFBSSxFQUFFLENBQUM7UUFDWCxDQUFDLENBQUMsQ0FBQTtJQUNOLENBQUMsQ0FBQyxDQUFDO0lBRUgsRUFBRSxDQUFDLHdCQUF3QixFQUFFLFVBQVUsSUFBSTtRQUN2QyxJQUFJLEtBQUssR0FBRyxlQUFlLENBQUMsVUFBVSxFQUFFLENBQUM7UUFDekMsSUFBSSxRQUFRLEdBQUcsbUJBQW1CLENBQUM7UUFDbkMsWUFBWSxDQUFDLE9BQU8sQ0FBQyxLQUFLLEVBQUUsUUFBUSxFQUFFLElBQUksRUFBRSxNQUFNLEVBQUUsRUFBRSxDQUFDLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxFQUFFO1lBQ2hFLE1BQU0sQ0FBQyxJQUFJLENBQUMsQ0FBQyxFQUFFLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FBQyxNQUFNLEVBQUUsUUFBUSxDQUFDLENBQUM7WUFDaEQsSUFBSSxFQUFFLENBQUM7UUFDWCxDQUFDLENBQUMsQ0FBQTtJQUNOLENBQUMsQ0FBQyxDQUFDO0lBRUgsRUFBRSxDQUFDLHNDQUFzQyxFQUFFLFVBQVUsSUFBSTtRQUNyRCxJQUFJLEtBQUssR0FBRyxlQUFlLENBQUMsVUFBVSxFQUFFLENBQUM7UUFDekMsSUFBSSxRQUFRLEdBQUcscUJBQXFCLENBQUM7UUFDckMsWUFBWSxDQUFDLE9BQU8sQ0FBQyxLQUFLLEVBQUUsUUFBUSxFQUFFLElBQUksRUFBRSxNQUFNLEVBQUUsRUFBRSxDQUFDLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxFQUFFO1lBQ2hFLE1BQU0sQ0FBQyxJQUFJLENBQUMsQ0FBQyxFQUFFLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FBQyxNQUFNLEVBQUUsUUFBUSxDQUFDLENBQUM7WUFDaEQsSUFBSSxFQUFFLENBQUM7UUFDWCxDQUFDLENBQUMsQ0FBQTtJQUNOLENBQUMsQ0FBQyxDQUFDO0lBRUgsUUFBUSxDQUFDLDBCQUEwQixFQUFFO1FBRWpDLEVBQUUsQ0FBQyxrQ0FBa0MsRUFBRSxVQUFVLElBQUk7WUFDakQsTUFBTSxVQUFVLEdBQW9CO2dCQUNoQyxJQUFJLEVBQUUsWUFBWTtnQkFDbEIsSUFBSSxFQUFFLE1BQU07Z0JBQ1osVUFBVSxFQUFFLElBQUk7Z0JBQ2hCLGNBQWMsRUFBRSxNQUFNO2dCQUN0QixzQkFBc0IsRUFBRTtvQkFDcEIsMEJBQTBCLEVBQUUsS0FBSztpQkFDcEM7Z0JBQ0QsY0FBYyxFQUFFLGtCQUFrQjtnQkFDbEMsb0JBQW9CLEVBQUUsS0FBSztnQkFDM0Isb0JBQW9CLEVBQUU7b0JBQ2xCO3dCQUNJLElBQUksRUFBRSxRQUFRO3dCQUNkLE1BQU0sRUFBRTs0QkFDSixLQUFLLEVBQUUsZUFBZTs0QkFDdEIsTUFBTSxFQUFFO2dDQUNKLEtBQUssRUFBRSx3Q0FBd0M7Z0NBQy9DLFFBQVEsRUFBRSxxQkFBcUI7NkJBQ2xDO3lCQUNKO3dCQUNELEtBQUssRUFBRTs0QkFDSCxLQUFLLEVBQUUsa0JBQWtCOzRCQUN6QixNQUFNLEVBQUU7Z0NBQ0osWUFBWSxFQUFFLGdCQUFnQjs2QkFDakM7eUJBQ0o7d0JBQ0QsU0FBUyxFQUFFOzRCQUNQLEtBQUssRUFBRSxzQkFBc0I7eUJBQ2hDO3dCQUNELFdBQVcsRUFBRTs0QkFDVCxhQUFhLEVBQUU7Z0NBQ1gsVUFBVSxFQUFFLEVBQUU7NkJBQ2pCOzRCQUNELFVBQVUsRUFBRSxFQUFFO3lCQUNqQjtxQkFDSjtpQkFDSjthQUNKLENBQUM7WUFDRixNQUFNLFFBQVEsR0FBb0I7Z0JBQzlCLElBQUksRUFBRSxZQUFZO2dCQUNsQixJQUFJLEVBQUUsTUFBTTtnQkFDWixVQUFVLEVBQUUsSUFBSTtnQkFDaEIsY0FBYyxFQUFFLE1BQU07Z0JBQ3RCLHNCQUFzQixFQUFFO29CQUNwQiwwQkFBMEIsRUFBRSxLQUFLO2lCQUNwQztnQkFDRCxjQUFjLEVBQUUsa0JBQWtCO2dCQUNsQyxvQkFBb0IsRUFBRSxLQUFLO2dCQUMzQixVQUFVLEVBQUUsRUFBRTtnQkFDZCxvQkFBb0IsRUFBRTtvQkFDbEI7d0JBQ0ksSUFBSSxFQUFFLFFBQVE7d0JBQ2QsTUFBTSxFQUFFOzRCQUNKLEtBQUssRUFBRSxlQUFlOzRCQUN0QixNQUFNLEVBQUU7Z0NBQ0osS0FBSyxFQUFFLHdDQUF3QztnQ0FDL0MsUUFBUSxFQUFFLHFCQUFxQjtnQ0FDL0IsU0FBUyxFQUFFLEtBQUs7Z0NBQ2hCLGFBQWEsRUFBRSxFQUFFO2dDQUNqQixRQUFRLEVBQUUsS0FBSztnQ0FDZixRQUFRLEVBQUUsSUFBSTtnQ0FDZCxlQUFlLEVBQUUsS0FBSztnQ0FDdEIscUJBQXFCLEVBQUUsS0FBSztnQ0FDNUIsZ0JBQWdCLEVBQUUsR0FBRztnQ0FDckIsUUFBUSxFQUFFLEtBQUs7Z0NBQ2YsT0FBTyxFQUFFLElBQUk7NkJBQ2hCO3lCQUNKO3dCQUNELEtBQUssRUFBRTs0QkFDSCxLQUFLLEVBQUUsa0JBQWtCOzRCQUN6QixNQUFNLEVBQUU7Z0NBQ0osS0FBSyxFQUFFLGdCQUFnQjs2QkFDMUI7eUJBQ0o7d0JBQ0QsU0FBUyxFQUFFOzRCQUNQLEtBQUssRUFBRSxzQkFBc0I7NEJBQzdCLE1BQU0sRUFBRTtnQ0FDSixTQUFTLEVBQUUsS0FBSztnQ0FDaEIsUUFBUSxFQUFFLEtBQUs7Z0NBQ2YsUUFBUSxFQUFFLElBQUk7Z0NBQ2QsUUFBUSxFQUFFLEtBQUs7Z0NBQ2YsSUFBSSxFQUFFLE1BQU07Z0NBQ1osT0FBTyxFQUFFLElBQUk7NkJBQ2hCO3lCQUNKO3FCQUNKO2lCQUNKO2FBQ0osQ0FBQztZQUNGLE1BQU0sUUFBUSxHQUFHLElBQUksQ0FBQyxTQUFTLENBQUMsVUFBVSxDQUFDLENBQUM7WUFDNUMsTUFBTSxNQUFNLEdBQUcsWUFBWSxDQUFDLHFCQUFxQixDQUFDLFVBQVUsQ0FBQyxDQUFDO1lBRTlELDhDQUE4QztZQUM5QyxNQUFNLENBQUMsSUFBSSxDQUFDLFNBQVMsQ0FBQyxVQUFVLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxHQUFHLENBQUMsUUFBUSxDQUFDLENBQUM7WUFFcEQsbURBQW1EO1lBQ25ELE1BQU0sQ0FBQyxNQUFNLENBQUMsQ0FBQyxFQUFFLENBQUMsR0FBRyxDQUFDLFFBQVEsQ0FBQyxDQUFDO1lBQ2hDLElBQUksRUFBRSxDQUFDO1FBQ1gsQ0FBQyxDQUFDLENBQUM7UUFDSCxFQUFFLENBQUMsK0VBQStFLEVBQUUsVUFBVSxJQUFJO1lBQzlGLE1BQU0sVUFBVSxHQUFvQjtnQkFDaEMsSUFBSSxFQUFFLDhCQUE4QjtnQkFDcEMsSUFBSSxFQUFFLE1BQU07Z0JBQ1osVUFBVSxFQUFFLElBQUk7Z0JBQ2hCLGNBQWMsRUFBRSxNQUFNO2dCQUN0QixzQkFBc0IsRUFBRTtvQkFDcEIsMEJBQTBCLEVBQUUsS0FBSztpQkFDcEM7Z0JBQ0QsY0FBYyxFQUFFLGtCQUFrQjtnQkFDbEMsb0JBQW9CLEVBQUUsS0FBSztnQkFDM0Isb0JBQW9CLEVBQUU7b0JBQ2xCO3dCQUNJLElBQUksRUFBRSxRQUFRO3dCQUNkLFNBQVMsRUFBRTs0QkFDUCxLQUFLLEVBQUUsc0JBQXNCO3lCQUNoQztxQkFDSjtvQkFDRDt3QkFDSSxJQUFJLEVBQUUsUUFBUTt3QkFDZCxNQUFNLEVBQUU7NEJBQ0osS0FBSyxFQUFFLGVBQWU7NEJBQ3RCLE1BQU0sRUFBRTtnQ0FDSixLQUFLLEVBQUUsd0NBQXdDO2dDQUMvQyxRQUFRLEVBQUUscUJBQXFCOzZCQUNsQzt5QkFDSjt3QkFDRCxLQUFLLEVBQUU7NEJBQ0gsS0FBSyxFQUFFLGtCQUFrQjs0QkFDekIsTUFBTSxFQUFFO2dDQUNKLFlBQVksRUFBRSxnQkFBZ0I7NkJBQ2pDO3lCQUNKO3dCQUNELFNBQVMsRUFBRTs0QkFDUCxLQUFLLEVBQUUsc0JBQXNCO3lCQUNoQzt3QkFDRCxXQUFXLEVBQUU7NEJBQ1QsYUFBYSxFQUFFO2dDQUNYLFVBQVUsRUFBRSxDQUFDLE9BQU8sRUFBRSxZQUFZLENBQUM7NkJBQ3RDOzRCQUNELFVBQVUsRUFBRSxFQUFFO3lCQUNqQjtxQkFDSjtpQkFDSjthQUNKLENBQUM7WUFDRixNQUFNLFFBQVEsR0FBb0I7Z0JBQzlCLElBQUksRUFBRSw4QkFBOEI7Z0JBQ3BDLElBQUksRUFBRSxNQUFNO2dCQUNaLFVBQVUsRUFBRSxJQUFJO2dCQUNoQixjQUFjLEVBQUUsTUFBTTtnQkFDdEIsc0JBQXNCLEVBQUU7b0JBQ3BCLDBCQUEwQixFQUFFLEtBQUs7aUJBQ3BDO2dCQUNELGNBQWMsRUFBRSxrQkFBa0I7Z0JBQ2xDLG9CQUFvQixFQUFFLEtBQUs7Z0JBQzNCLFVBQVUsRUFBRSxFQUFFO2dCQUNkLG9CQUFvQixFQUFFO29CQUNsQjt3QkFDSSxJQUFJLEVBQUUsUUFBUTt3QkFDZCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHNCQUFzQjs0QkFDN0IsTUFBTSxFQUFFO2dDQUNKLFNBQVMsRUFBRSxLQUFLO2dDQUNoQixRQUFRLEVBQUUsS0FBSztnQ0FDZixRQUFRLEVBQUUsSUFBSTtnQ0FDZCxRQUFRLEVBQUUsS0FBSztnQ0FDZixJQUFJLEVBQUUsTUFBTTtnQ0FDWixPQUFPLEVBQUUsSUFBSTs2QkFDaEI7eUJBQ0o7cUJBQ0o7aUJBQ0o7YUFDSixDQUFDO1lBQ0YsTUFBTSxRQUFRLEdBQUcsSUFBSSxDQUFDLFNBQVMsQ0FBQyxVQUFVLENBQUMsQ0FBQztZQUM1QyxNQUFNLE1BQU0sR0FBRyxZQUFZLENBQUMscUJBQXFCLENBQUMsVUFBVSxDQUFDLENBQUM7WUFFOUQsOENBQThDO1lBQzlDLE1BQU0sQ0FBQyxJQUFJLENBQUMsU0FBUyxDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLEdBQUcsQ0FBQyxRQUFRLENBQUMsQ0FBQztZQUVwRCxtREFBbUQ7WUFDbkQsTUFBTSxDQUFDLE1BQU0sQ0FBQyxDQUFDLEVBQUUsQ0FBQyxHQUFHLENBQUMsUUFBUSxDQUFDLENBQUM7WUFDaEMsSUFBSSxFQUFFLENBQUM7UUFDWCxDQUFDLENBQUMsQ0FBQztRQUNILEVBQUUsQ0FBQyxnRkFBZ0YsRUFBRSxVQUFVLElBQUk7WUFDL0YsTUFBTSxVQUFVLEdBQW9CO2dCQUNoQyxJQUFJLEVBQUUsNkJBQTZCO2dCQUNuQyxJQUFJLEVBQUUsTUFBTTtnQkFDWixVQUFVLEVBQUUsSUFBSTtnQkFDaEIsY0FBYyxFQUFFLE1BQU07Z0JBQ3RCLHNCQUFzQixFQUFFO29CQUNwQiwwQkFBMEIsRUFBRSxLQUFLO2lCQUNwQztnQkFDRCxjQUFjLEVBQUUsa0JBQWtCO2dCQUNsQyxvQkFBb0IsRUFBRSxLQUFLO2dCQUMzQixvQkFBb0IsRUFBRTtvQkFDbEI7d0JBQ0ksSUFBSSxFQUFFLFFBQVE7d0JBQ2QsU0FBUyxFQUFFOzRCQUNQLEtBQUssRUFBRSxzQkFBc0I7eUJBQ2hDO3FCQUNKO29CQUNEO3dCQUNJLElBQUksRUFBRSxRQUFRO3dCQUNkLE1BQU0sRUFBRTs0QkFDSixLQUFLLEVBQUUsZUFBZTs0QkFDdEIsTUFBTSxFQUFFO2dDQUNKLEtBQUssRUFBRSx3Q0FBd0M7Z0NBQy9DLFFBQVEsRUFBRSxxQkFBcUI7NkJBQ2xDO3lCQUNKO3dCQUNELEtBQUssRUFBRTs0QkFDSCxLQUFLLEVBQUUsa0JBQWtCOzRCQUN6QixNQUFNLEVBQUU7Z0NBQ0osWUFBWSxFQUFFLGdCQUFnQjs2QkFDakM7eUJBQ0o7d0JBQ0QsU0FBUyxFQUFFOzRCQUNQLEtBQUssRUFBRSxzQkFBc0I7eUJBQ2hDO3dCQUNELFdBQVcsRUFBRTs0QkFDVCxhQUFhLEVBQUU7Z0NBQ1gsUUFBUSxFQUFFLHVDQUF1Qzs2QkFDcEQ7eUJBQ0o7d0JBQ0QsV0FBVyxFQUFFOzRCQUNULGFBQWEsRUFBRTtnQ0FDWCxVQUFVLEVBQUUsRUFBRTs2QkFDakI7NEJBQ0QsVUFBVSxFQUFFLENBQUMsTUFBTSxDQUFDO3lCQUN2QjtxQkFDSjtpQkFDSjthQUNKLENBQUM7WUFDRixNQUFNLFFBQVEsR0FBb0I7Z0JBQzlCLElBQUksRUFBRSw2QkFBNkI7Z0JBQ25DLElBQUksRUFBRSxNQUFNO2dCQUNaLFVBQVUsRUFBRSxJQUFJO2dCQUNoQixjQUFjLEVBQUUsTUFBTTtnQkFDdEIsc0JBQXNCLEVBQUU7b0JBQ3BCLDBCQUEwQixFQUFFLEtBQUs7aUJBQ3BDO2dCQUNELGNBQWMsRUFBRSxrQkFBa0I7Z0JBQ2xDLG9CQUFvQixFQUFFLEtBQUs7Z0JBQzNCLFVBQVUsRUFBRSxFQUFFO2dCQUNkLG9CQUFvQixFQUFFO29CQUNsQjt3QkFDSSxJQUFJLEVBQUUsUUFBUTt3QkFDZCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHNCQUFzQjs0QkFDN0IsTUFBTSxFQUFFO2dDQUNKLFNBQVMsRUFBRSxLQUFLO2dDQUNoQixRQUFRLEVBQUUsS0FBSztnQ0FDZixRQUFRLEVBQUUsSUFBSTtnQ0FDZCxRQUFRLEVBQUUsS0FBSztnQ0FDZixJQUFJLEVBQUUsTUFBTTtnQ0FDWixPQUFPLEVBQUUsSUFBSTs2QkFDaEI7eUJBQ0o7cUJBQ0o7aUJBRUo7YUFDSixDQUFDO1lBQ0YsTUFBTSxRQUFRLEdBQUcsSUFBSSxDQUFDLFNBQVMsQ0FBQyxVQUFVLENBQUMsQ0FBQztZQUM1QyxNQUFNLE1BQU0sR0FBRyxZQUFZLENBQUMscUJBQXFCLENBQUMsVUFBVSxDQUFDLENBQUM7WUFFOUQsOENBQThDO1lBQzlDLE1BQU0sQ0FBQyxJQUFJLENBQUMsU0FBUyxDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLEdBQUcsQ0FBQyxRQUFRLENBQUMsQ0FBQztZQUVwRCxtREFBbUQ7WUFDbkQsTUFBTSxDQUFDLE1BQU0sQ0FBQyxDQUFDLEVBQUUsQ0FBQyxHQUFHLENBQUMsUUFBUSxDQUFDLENBQUM7WUFDaEMsSUFBSSxFQUFFLENBQUM7UUFDWCxDQUFDLENBQUMsQ0FBQztRQUNILEVBQUUsQ0FBQyx5R0FBeUcsRUFBRSxVQUFVLElBQUk7WUFDeEgsTUFBTSxVQUFVLEdBQW9CO2dCQUNoQyxJQUFJLEVBQUUsZ0NBQWdDO2dCQUN0QyxJQUFJLEVBQUUsTUFBTTtnQkFDWixVQUFVLEVBQUUsSUFBSTtnQkFDaEIsY0FBYyxFQUFFLE1BQU07Z0JBQ3RCLHNCQUFzQixFQUFFO29CQUNwQiwwQkFBMEIsRUFBRSxLQUFLO2lCQUNwQztnQkFDRCxjQUFjLEVBQUUsa0JBQWtCO2dCQUNsQyxvQkFBb0IsRUFBRSxLQUFLO2dCQUMzQixvQkFBb0IsRUFBRTtvQkFDbEI7d0JBQ0ksSUFBSSxFQUFFLG9CQUFvQjt3QkFDMUIsS0FBSyxFQUFFOzRCQUNILEtBQUssRUFBRSxpQkFBaUI7NEJBQ3hCLE1BQU0sRUFBRSxFQUFDLFlBQVksRUFBRSxDQUFDLEVBQUMsTUFBTSxFQUFFLG1DQUFtQyxFQUFDLENBQUMsRUFBQzt5QkFDMUU7d0JBQ0QsU0FBUyxFQUFFOzRCQUNQLEtBQUssRUFBRSxxQkFBcUI7NEJBQzVCLE1BQU0sRUFBRTtnQ0FDSixlQUFlLEVBQUU7b0NBQ2IsSUFBSSxFQUFFLEVBQUU7b0NBQ1IsS0FBSyxFQUFFLEVBQUMsS0FBSyxFQUFFLFlBQVksRUFBRSxNQUFNLEVBQUUsRUFBQyxZQUFZLEVBQUUsRUFBRSxFQUFDLEVBQUM7b0NBQ3hELFNBQVMsRUFBRTt3Q0FDUCxLQUFLLEVBQUUsZ0JBQWdCO3dDQUN2QixNQUFNLEVBQUU7NENBQ0osaUJBQWlCLEVBQUUsS0FBSzs0Q0FDeEIsb0JBQW9CLEVBQUU7Z0RBQ2xCO29EQUNJLDhDQUE4QztvREFDOUMsSUFBSSxFQUFFLFFBQVE7b0RBQ2QsS0FBSyxFQUFFO3dEQUNILEtBQUssRUFBRSxrQkFBa0I7d0RBQ3pCLE1BQU0sRUFBRSxFQUFDLFlBQVksRUFBRSxnQkFBZ0IsR0FBRTtxREFDNUM7b0RBQ0QsU0FBUyxFQUFFLEVBQUMsS0FBSyxFQUFFLHNCQUFzQixFQUFDO29EQUMxQyxXQUFXLEVBQUUsRUFBQyxVQUFVLEVBQUUsQ0FBQyxNQUFNLENBQUMsRUFBQztpREFDdEM7Z0RBQ0Q7b0RBQ0ksSUFBSSxFQUFFLFFBQVE7b0RBQ2QsS0FBSyxFQUFFO3dEQUNILEtBQUssRUFBRSxrQkFBa0I7d0RBQ3pCLE1BQU0sRUFBRSxFQUFDLFlBQVksRUFBRSxnQkFBZ0IsRUFBQztxREFDM0M7b0RBQ0QsU0FBUyxFQUFFLEVBQUMsS0FBSyxFQUFFLHNCQUFzQixFQUFDO2lEQUM3QztnREFDRDtvREFDSSx1Q0FBdUM7b0RBQ3ZDLElBQUksRUFBRSxzQkFBc0I7b0RBQzVCLEtBQUssRUFBRSxFQUFDLEtBQUssRUFBRSxpQkFBaUIsRUFBRSxNQUFNLEVBQUUsRUFBRSxFQUFDO29EQUM3QyxTQUFTLEVBQUU7d0RBQ1AsS0FBSyxFQUFFLHFCQUFxQjt3REFDNUIsTUFBTSxFQUFFOzREQUNKLGVBQWUsRUFBRTtnRUFDYixJQUFJLEVBQUUsSUFBSTtnRUFDVixLQUFLLEVBQUU7b0VBQ0gsS0FBSyxFQUFFLGtCQUFrQjtvRUFDekIsTUFBTSxFQUFFLEVBQUMsWUFBWSxFQUFFLHVDQUF1QyxFQUFDO2lFQUNsRTtnRUFDRCxTQUFTLEVBQUUsRUFBQyxLQUFLLEVBQUUsc0JBQXNCLEVBQUM7Z0VBQzFDLFdBQVcsRUFBRSxFQUFDLGFBQWEsRUFBRSxFQUFDLFVBQVUsRUFBRSxDQUFDLE9BQU8sQ0FBQyxFQUFDLEVBQUM7NkRBQ3hEO3lEQUNKO3FEQUNKO2lEQUNKOzZDQUNKO3lDQUNKO3FDQUNKO29DQUNELE1BQU0sRUFBRTt3Q0FDSixLQUFLLEVBQUUseUJBQXlCO3dDQUNoQyxNQUFNLEVBQUUsRUFBQyxjQUFjLEVBQUUsdUJBQXVCLEVBQUM7cUNBQ3BEO29DQUNELGlDQUFpQztvQ0FDakMsV0FBVyxFQUFFLEVBQUMsYUFBYSxFQUFFLEVBQUMsVUFBVSxFQUFFLEVBQUUsRUFBQyxFQUFFLFVBQVUsRUFBRSxDQUFDLE1BQU0sQ0FBQyxFQUFDO2lDQUN2RTs2QkFDSjt5QkFDSjt3QkFDRCxNQUFNLEVBQUU7NEJBQ0osS0FBSyxFQUFFLGVBQWU7NEJBQ3RCLE1BQU0sRUFBRTtnQ0FDSixLQUFLLEVBQUUsbURBQW1EO2dDQUMxRCxRQUFRLEVBQUUsZ0NBQWdDOzZCQUM3Qzt5QkFDSjtxQkFDSjtpQkFDSjthQUNKLENBQUM7WUFDRixNQUFNLFFBQVEsR0FBb0I7Z0JBQzlCLElBQUksRUFBRSxnQ0FBZ0M7Z0JBQ3RDLElBQUksRUFBRSxNQUFNO2dCQUNaLFVBQVUsRUFBRSxJQUFJO2dCQUNoQixjQUFjLEVBQUUsTUFBTTtnQkFDdEIsc0JBQXNCLEVBQUU7b0JBQ3BCLDBCQUEwQixFQUFFLEtBQUs7aUJBQ3BDO2dCQUNELGNBQWMsRUFBRSxrQkFBa0I7Z0JBQ2xDLG9CQUFvQixFQUFFLEtBQUs7Z0JBQzNCLFVBQVUsRUFBRSxFQUFFO2dCQUNkLG9CQUFvQixFQUFFO29CQUNsQjt3QkFDSSxJQUFJLEVBQUUsb0JBQW9CO3dCQUMxQixLQUFLLEVBQUU7NEJBQ0gsS0FBSyxFQUFFLGlCQUFpQjs0QkFDeEIsTUFBTSxFQUFFLEVBQUMsS0FBSyxFQUFFLENBQUMsRUFBQyxNQUFNLEVBQUUsbUNBQW1DLEVBQUMsQ0FBQyxFQUFDO3lCQUNuRTt3QkFDRCxTQUFTLEVBQUU7NEJBQ1AsS0FBSyxFQUFFLHFCQUFxQjs0QkFDNUIsTUFBTSxFQUFFO2dDQUNKLFNBQVMsRUFBRSxLQUFLO2dDQUNoQixRQUFRLEVBQUUsS0FBSztnQ0FDZixRQUFRLEVBQUUsSUFBSTtnQ0FDZCxRQUFRLEVBQUUsS0FBSztnQ0FDZixPQUFPLEVBQUUsSUFBSTtnQ0FDYixlQUFlLEVBQUU7b0NBQ2IsSUFBSSxFQUFFLEVBQUU7b0NBQ1IsS0FBSyxFQUFFLEVBQUMsS0FBSyxFQUFFLFlBQVksRUFBRSxNQUFNLEVBQUUsRUFBRSxFQUFDO29DQUN4QyxTQUFTLEVBQUU7d0NBQ1AsS0FBSyxFQUFFLGdCQUFnQjt3Q0FDdkIsTUFBTSxFQUFFOzRDQUNKLFNBQVMsRUFBRSxLQUFLOzRDQUNoQixRQUFRLEVBQUUsS0FBSzs0Q0FDZixRQUFRLEVBQUUsSUFBSTs0Q0FDZCxRQUFRLEVBQUUsS0FBSzs0Q0FDZixPQUFPLEVBQUUsSUFBSTs0Q0FDYixpQkFBaUIsRUFBRSxLQUFLOzRDQUN4QixvQkFBb0IsRUFBRTtnREFDbEIsa0RBQWtEO2dEQUNsRDtvREFDSSxJQUFJLEVBQUUsUUFBUTtvREFDZCxLQUFLLEVBQUU7d0RBQ0gsS0FBSyxFQUFFLGtCQUFrQjt3REFDekIsTUFBTSxFQUFFLEVBQUU7cURBQ2I7b0RBQ0QsU0FBUyxFQUFFO3dEQUNQLEtBQUssRUFBRSxzQkFBc0I7d0RBQzdCLE1BQU0sRUFBRTs0REFDSixTQUFTLEVBQUUsS0FBSzs0REFDaEIsUUFBUSxFQUFFLEtBQUs7NERBQ2YsUUFBUSxFQUFFLElBQUk7NERBQ2QsUUFBUSxFQUFFLEtBQUs7NERBQ2YsSUFBSSxFQUFFLE1BQU07NERBQ1osT0FBTyxFQUFFLElBQUk7eURBQ2hCO3FEQUNKO2lEQUNKO2dEQUNELDJDQUEyQzs2Q0FDOUM7eUNBQ0o7cUNBQ0o7b0NBQ0QsTUFBTSxFQUFFO3dDQUNKLEtBQUssRUFBRSx5QkFBeUI7d0NBQ2hDLE1BQU0sRUFBRTs0Q0FDSixjQUFjLEVBQUUsdUJBQXVCOzRDQUN2QyxTQUFTLEVBQUUsS0FBSzs0Q0FDaEIsYUFBYSxFQUFFLEVBQUU7NENBQ2pCLFFBQVEsRUFBRSxLQUFLOzRDQUNmLFFBQVEsRUFBRSxJQUFJOzRDQUNkLGVBQWUsRUFBRSxLQUFLOzRDQUN0QixxQkFBcUIsRUFBRSxLQUFLOzRDQUM1QixnQkFBZ0IsRUFBRSxHQUFHOzRDQUNyQixRQUFRLEVBQUUsS0FBSzs0Q0FDZixPQUFPLEVBQUUsSUFBSTt5Q0FDaEI7cUNBQ0o7b0NBQ0QsMERBQTBEO2lDQUM3RDs2QkFDSjt5QkFDSjt3QkFDRCxNQUFNLEVBQUU7NEJBQ0osS0FBSyxFQUFFLGVBQWU7NEJBQ3RCLE1BQU0sRUFBRTtnQ0FDSixLQUFLLEVBQUUsbURBQW1EO2dDQUMxRCxRQUFRLEVBQUUsZ0NBQWdDO2dDQUMxQyxTQUFTLEVBQUUsS0FBSztnQ0FDaEIsYUFBYSxFQUFFLEVBQUU7Z0NBQ2pCLFFBQVEsRUFBRSxLQUFLO2dDQUNmLFFBQVEsRUFBRSxJQUFJO2dDQUNkLGVBQWUsRUFBRSxLQUFLO2dDQUN0QixxQkFBcUIsRUFBRSxLQUFLO2dDQUM1QixnQkFBZ0IsRUFBRSxHQUFHO2dDQUNyQixRQUFRLEVBQUUsS0FBSztnQ0FDZixPQUFPLEVBQUUsSUFBSTs2QkFDaEI7eUJBQ0o7cUJBQ0o7aUJBQ0o7YUFDSixDQUFDO1lBQ0YsTUFBTSxRQUFRLEdBQUcsSUFBSSxDQUFDLFNBQVMsQ0FBQyxVQUFVLENBQUMsQ0FBQztZQUM1QyxNQUFNLE1BQU0sR0FBRyxZQUFZLENBQUMscUJBQXFCLENBQUMsVUFBVSxDQUFDLENBQUM7WUFFOUQsOENBQThDO1lBQzlDLE1BQU0sQ0FBQyxJQUFJLENBQUMsU0FBUyxDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLEdBQUcsQ0FBQyxRQUFRLENBQUMsQ0FBQztZQUVwRCxtREFBbUQ7WUFDbkQsTUFBTSxDQUFDLE1BQU0sQ0FBQyxDQUFDLEVBQUUsQ0FBQyxHQUFHLENBQUMsUUFBUSxDQUFDLENBQUM7WUFDaEMsSUFBSSxFQUFFLENBQUM7UUFDWCxDQUFDLENBQUMsQ0FBQztJQUNQLENBQUMsQ0FBQyxDQUFDO0FBQ1AsQ0FBQyxDQUFDLENBQUMifQ==