'use strict';
/**
 * models config shim
 * Auto-generated by redbox-loader.js
 * Provided by: @researchdatabox/redbox-core-types
 * Do not edit manually - regenerated when .regenerate-shims marker exists
 */
const { Config } = require('@researchdatabox/redbox-core-types');
module.exports.models = Config.models;
