help:
	    @echo "_______BUILD ANGULAR FRONTEND______\n"
	    @echo "To build all apps run make make build-frontend"

build-frontend:
			@echo "Building local_auth"
	    ng build -a=0 --extract-css true
			@echo "Building dashboard"
			ng build -a=1 --extract-css true
			@echo "Building record_search"
			ng build -a=2 --extract-css true
			@echo "Building transfer_owner"
			ng build -a=3 --extract-css true
			@echo "Building report"
			ng build -a=4 --extract-css true
			@echo "Building manageRoles"
			ng build -a=5 --extract-css true
			@echo "Building manageUsers"
			ng build -a=6 --extract-css true
			@echo "Building export"
			ng build -a=7 --extract-css true
			@echo "Building userProfile"
			ng build -a=8 --extract-css true
			@echo "Building dmp"
			ng build -a=9 --extract-css true
			@echo "Building workspace_list"
			ng build -a=10 --extract-css true

build-frontend-prod:
			@echo "Building local_auth"
	    ng build -a=0 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building dashboard"
			ng build -a=1 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building record_search"
			ng build -a=2 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building transfer_owner"
			ng build -a=3 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building report"
			ng build -a=4 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building manageRoles"
			ng build -a=5 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building manageUsers"
			ng build -a=6 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building export"
			ng build -a=7 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building userProfile"
			ng build -a=8 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building dmp"
			ng build -a=9 --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building workspace_list"
			ng build -a=10 --prod --build-optimizer --output-hashing=none --extract-css true

build-frontend-prod-sourcemaps:
			@echo "Building local_auth"
	    ng build -a=0 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building dashboard"
			ng build -a=1 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building record_search"
			ng build -a=2 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building transfer_owner"
			ng build -a=3 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building report"
			ng build -a=4 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building manageRoles"
			ng build -a=5 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building manageUsers"
			ng build -a=6 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building export"
			ng build -a=7 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building userProfile"
			ng build -a=8 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building dmp"
			ng build -a=9 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building workspace_list"
			ng build -a=10 --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
