help:
	    @echo "_______BUILD ANGULAR FRONTEND______\n"
	    @echo "To build all apps run make make build-frontend"

build-frontend:
			@echo "Building local_auth"
	    ng build -a=0
			@echo "Building dashboard"
			ng build -a=1
			@echo "Building record_search"
			ng build -a=2
			@echo "Building transfer_owner"
			ng build -a=3
			@echo "Building report"
			ng build -a=4
			@echo "Building manageRoles"
			ng build -a=5
			@echo "Building manageUsers"
			ng build -a=6
			@echo "Building export"
			ng build -a=7
			@echo "Building userProfile"
			ng build -a=8
			@echo "Building dmp"
			ng build -a=9

build-frontend-prod:
			@echo "Building local_auth"
	    ng build -a=0 --prod --build-optimizer --output-hashing=none
			@echo "Building dashboard"
			ng build -a=1 --prod --build-optimizer --output-hashing=none
			@echo "Building record_search"
			ng build -a=2 --prod --build-optimizer --output-hashing=none
			@echo "Building transfer_owner"
			ng build -a=3 --prod --build-optimizer --output-hashing=none
			@echo "Building report"
			ng build -a=4 --prod --build-optimizer --output-hashing=none
			@echo "Building manageRoles"
			ng build -a=5 --prod --build-optimizer --output-hashing=none
			@echo "Building manageUsers"
			ng build -a=6 --prod --build-optimizer --output-hashing=none
			@echo "Building export"
			ng build -a=7 --prod --build-optimizer --output-hashing=none
			@echo "Building userProfile"
			ng build -a=8 --prod --build-optimizer --output-hashing=none
			@echo "Building dmp"
			ng build -a=9 --prod --build-optimizer --output-hashing=none
