import * as path from 'path';
import * as fs from 'fs';
import { Generator, GeneratorOptions } from '../utils/generator';
import { RedboxPaths } from '../utils/paths';

export interface AngularServiceGeneratorOptions extends GeneratorOptions {
  app: string;
  name: string;
  methods?: string[];
  paths: RedboxPaths;
}

export class AngularServiceGenerator extends Generator {
  private app: string;
  private name: string;
  private methods: string[];
  private paths: RedboxPaths;

  constructor(options: AngularServiceGeneratorOptions) {
    super(options);
    this.app = options.app.toLowerCase();
    this.name = options.name.toLowerCase();
    this.methods = options.methods || [];
    this.paths = options.paths;
  }

  public async generate(): Promise<void> {
    const projectRoot = path.join(this.paths.angular, 'projects', 'researchdatabox', this.app);
    if (!fs.existsSync(projectRoot)) {
      throw new Error(`Angular app project not found at: ${projectRoot}`);
    }

    const serviceClassName = this.toClassName(this.name);
    const fileName = `${this.name}.service.ts`;
    const servicePath = path.join(projectRoot, 'src', 'app', fileName);

    const content = this.generateServiceContent(serviceClassName);
    this.writeFile(servicePath, content);
  }

  private generateServiceContent(serviceClassName: string): string {
    const className = `${serviceClassName}Service`;
    
    let methodsContent = '';
    if (this.methods.length > 0) {
      methodsContent = this.methods.map(method => `
  /**
   * ${this.capitalize(method)}
   */
  public async ${method}(): Promise<any> {
    const url = \`\${this.brandingAndPortalUrl}/app/${this.app}/${method}\`;
    const result$ = this.http.get(url, { ...this.reqOptsJsonBodyOnly, context: this.httpContext });
    return await firstValueFrom(result$);
  }
`).join('\n');
    }

    return `import { Injectable, Inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { APP_BASE_HREF } from '@angular/common';
import { HttpClientService, ConfigService, UtilityService } from '@researchdatabox/portal-ng-common';
import { firstValueFrom } from 'rxjs';

/**
 * ${serviceClassName} Service
 * 
 * Generated by ReDBox Hook Kit
 */
@Injectable({
  providedIn: 'root'
})
export class ${className} extends HttpClientService {

  constructor(
    @Inject(HttpClient) http: HttpClient,
    @Inject(APP_BASE_HREF) rootContext: string,
    @Inject(UtilityService) utilService: UtilityService,
    @Inject(ConfigService) configService: ConfigService
  ) {
    super(http, rootContext, utilService, configService);
  }

  public override async waitForInit(): Promise<any> {
    await super.waitForInit(); 
    this.enableCsrfHeader();
    return this;
  }
${methodsContent}
}
`;
  }

  private toClassName(name: string): string {
    return name.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('');
  }

  private capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
}
