'use strict';
/**
 * emailnotification config shim
 * Auto-generated by @researchdatabox/redbox-core loader
 * Do not edit manually - regenerated when .regenerate-shims marker exists
 *
 * Merges: core config + hook configs (alphabetical order)
 * Debug view: see support/debug-config/resolved.js
 */
const _ = require('lodash');
const { Config } = require('@researchdatabox/redbox-core');
const _researchdatabox_sails_hook_redbox_storage_mongo_config = require('@researchdatabox/sails-hook-redbox-storage-mongo').registerRedboxConfig();

module.exports.emailnotification = _.merge({}, Config.emailnotification || {}, _researchdatabox_sails_hook_redbox_storage_mongo_config['emailnotification'] || {});
