name: pdfgen-development

networks:
  main:

services:
  rbportal:
    build:
      context: "../../../.."
      dockerfile: "Dockerfile"
      target: "runtime_pdfgen"
    ports:
      - "1500:1500"
      - "9876:9876"
    volumes:
      - "../../:/opt/redbox-portal/node_modules/@researchdatabox/sails-hook-redbox-pdfgen"
      - "../api-integration-testing/recordtype.config.js:/opt/redbox-portal/node_modules/@researchdatabox/redbox-core/dist/config/recordtype.config.js:delegated"
      - "./.tmp/attachments/staging:/attachments/staging"
    expose:
      - "1500"
    environment:
      - NODE_ENV=docker
      - NODE_PATH=/opt/redbox-portal/node_modules:/opt/redbox-portal/node_modules/@researchdatabox/redbox-core/node_modules
      - LOAD_DEFAULT_FORMS=true
      - PORT=1500
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - sails_appUrl=http://localhost:1500
      # - sails_angularDev='true'
      - sails_brandingConfigurationDefaults__auth__local__default__token=6b088b4d-d54c-470c-8568-2f2695fcdab9
      - sails_brandingConfigurationDefaults__pdfgen__token=6b088b4d-d54c-470c-8568-2f2695fcdab9
    networks:
      main:
        aliases:
          - rbportal
    entrypoint: >-
      /bin/bash -c "set -x;
      cd /opt/redbox-portal &&
      node --enable-source-maps --inspect=0.0.0.0:9876 app.js;"

  mongodb:
    image: mongo:7
    networks:
      main:
        aliases:
          - mongodb
    ports:
      - "27017:27017"
    volumes:
      - ".tmp/mongo:/data/db"

  solr:
    image: solr:8.11.1
    networks:
      main:
        aliases:
          - solr
    expose:
      - "8983"
    ports:
      - "8983:8983"
    environment:
      - SOLR_HOME=/var/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - redbox
