import { FormsService as FormsModule, BrandingService as BrandingModule } from "@researchdatabox/redbox-core-types";
import { FormConfigFrame } from "@researchdatabox/sails-ng-common";

let expect: Chai.ExpectStatic;
import("chai").then(mod => expect = mod.expect);


declare const FormsService: FormsModule.Services.Forms;
declare const BrandingService: BrandingModule.Services.Branding;
declare const RecordType: any;
declare const sails: any;

describe('The FormsService', function () {
    before(function (done) {
        done();
    });

    const makeCompConfig = function (data) {
        return Object.assign({}, {
            autofocus: false,
            disabled: false,
            editMode: true,
            readonly: false,
            visible: true,
        }, data);
    }

    it('should return the default RDMP form', function (done) {
        var brand = BrandingService.getDefault();
        var recordType = 'rdmp';
        var formName = 'default-1.0-draft';
        RecordType.find().then(forms => {
            sails.log.verbose(`going to look for ${brand.id}_${recordType}`);
            sails.log.verbose(forms);
        });
        console.log('brand.id ' + brand.id + ' recordType ' + recordType);
        FormsService.getFormByStartingWorkflowStep(brand, recordType, true).subscribe(function (form) {
            expect(form).to.have.property('name', formName);
            done();
        })
    });

    it.skip('should get dataPublication-1.0-embargoed form (skipped: legacy form not yet migrated to FormConfigFrame)', function (done) {

        var formName = 'dataPublication-1.0-embargoed';

        FormsService.getFormByName(formName, true).subscribe(function (form) {
            console.log(form)
            expect(form).to.have.property('name', formName);
            done();
        })
    });

    it('should return the form based of a given record', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'default-1.0-draft';
        let record = {
            metaMetadata: {
                form: formName,
                type: 'rdmp'
            }
        };
        FormsService.getForm(brand, '', true, '', record).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        })
    });

    it('should return the autogenerated form based of a given record', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'generated-view-only';
        let record = {
            metaMetadata: {
                form: formName,
                type: 'rdmp'
            },
            metadata: {
                ID: 's823456',
                GIVEN_NAME: 'Ant10',
                OTHER_NAMES: 'Other',
                FAMILY_NAME: 'Season',
                PREF_NAME: 'Ant',
                HONORIFIC: 'Sr',
                EMAIL: 'notAReal@email.edu.au',
                JOB_TITLE: 'Assistant Professor',
                NLA_PARTY_IDENTIFIER: '',
                URIs: ['URI1', 'URI2', 'URI3'],
                ORCID: '0000-0001-7269-2286',
                PERSONAL_HOMEPAGE: '',
                STAFF_PROFILE_HOMEPAGE: '',
                DESCRIPTION: '',
                RESEARCH_ELEMENTS_USER_ID: '12345678',
                contributor_ci: {
                    text_full_name: 'Prof Ant10 Season',
                    email: 'notAReal@email.edu.au',
                    orcid: 'http://orcid.org/0000-0000-0000-000'
                },
                contributor_data_manager: [{
                    text_full_name: 'Prof Ant Season',
                    email: 'notAReal@email.edu.au',
                    orcid: 'http://orcid.org/0000-0000-0000-000'
                }]
            }
        };

        FormsService.getForm(brand, '', true, '', record).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        })
    });

    it('should return the form', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'default-1.0-draft';
        FormsService.getForm(brand, formName, true, 'rdmp', {}).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        })
    });

    it('should return the autogenerated form', function (done) {
        let brand = BrandingService.getDefault();
        let formName = 'generated-view-only';
        FormsService.getForm(brand, formName, true, 'rdmp', {}).then(form => {
            expect(form).to.have.property('name', formName);
            done();
        })
    });

    describe("build client form config", function () {
        it('should use the record data in the form edit mode', async function () {
            const formConfig: FormConfigFrame = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                componentDefinitions: [
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        constraints: {
                            authorization: {
                                allowRoles: [],
                            },
                            allowModes: [],
                        },
                    }
                ]
            };
            const expected: FormConfigFrame = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                validators: [],
                validationGroups: {
                    all: { description: "Validate all fields with validators.", initialMembership: "all" },
                    none: { description: "Validate none of the fields.", initialMembership: "none" },
                },
                componentDefinitions: [
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                                autofocus: false,
                                cssClassesMap: {},
                                disabled: false,
                                editMode: true,
                                helpTextVisible: false,
                                helpTextVisibleOnInit: false,
                                labelRequiredStr: "*",
                                readonly: false,
                                visible: true,
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                value: "record text_2 value",
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                            config: {
                                autofocus: false,
                                disabled: false,
                                editMode: true,
                                readonly: false,
                                type: "text",
                                visible: true,
                            },
                        },
                    }
                ]
            };
            const recordMetadata = {
                text_2: "record text_2 value"
            };
            const original = JSON.stringify(formConfig);
            const result = await FormsService.buildClientFormConfig(formConfig, "edit", null, recordMetadata);

            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);

            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
        });
        it('should use the record data in the form view mode', async function () {
            const formConfig: FormConfigFrame = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: { class: 'SimpleInputComponent' }
                    },
                    {
                        name: 'repeatable_1',
                        component: {
                            class: 'RepeatableComponent', config: {
                                elementTemplate: {
                                    name: "",
                                    component: {
                                        class: "GroupComponent", config: {
                                            componentDefinitions: [
                                                {
                                                    name: 'text_2',
                                                    component: { class: 'SimpleInputComponent' }
                                                },
                                                {
                                                    name: "repeatable_2",
                                                    component: {
                                                        class: "RepeatableComponent", config: {
                                                            elementTemplate: {
                                                                name: "",
                                                                component: {
                                                                    class: "GroupComponent", config: {
                                                                        componentDefinitions: [
                                                                            {
                                                                                name: 'text_3',
                                                                                component: { class: 'SimpleInputComponent' }
                                                                            },
                                                                            {
                                                                                name: 'group_1',
                                                                                component: {
                                                                                    class: 'GroupComponent', config: {
                                                                                        componentDefinitions: [
                                                                                            {
                                                                                                name: 'text_4',
                                                                                                component: { class: 'SimpleInputComponent' }
                                                                                            },
                                                                                        ]
                                                                                    }
                                                                                }
                                                                            },
                                                                        ]
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                    }
                ]
            };
            const expected: FormConfigFrame = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                validators: [],
                validationGroups: {
                    all: { description: "Validate all fields with validators.", initialMembership: "all" },
                    none: { description: "Validate none of the fields.", initialMembership: "none" },
                },
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'ContentComponent',
                            config: makeCompConfig({
                                content: "value text_1",
                                template: `<span>{{content}}</span>`
                            })
                        },
                    },
                    {
                        name: 'repeatable_1',
                        // TODO: As view mode transforms SimpleInput to Content component,
                        //  groups & repeatables may need at least one nested FormControl,
                        //  and Content components don't have a model, so no form control.
                        //  To discuss: does this make sense, or is there a different approach?
                        model: {
                            class: "RepeatableModel",
                            config: {
                                value: [
                                    {
                                        repeatable_2: [
                                            {
                                                text_3: "value repeatable_1.0.repeatable_2.0.text_3",
                                                group_1: {
                                                    text_4: "value repeatable_1.0.repeatable_2.0.group_1.text_4",
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        text_2: "value repeatable_1.1.text_2",
                                        repeatable_2: [
                                            {
                                                text_3: "value repeatable_1.1.repeatable_2.0.text_3",
                                            }
                                        ]
                                    }
                                ]
                            }
                        },
                        component: {
                            class: 'RepeatableComponent', config: makeCompConfig({
                                elementTemplate: {
                                    name: "",
                                    component: {
                                        class: "GroupComponent", config: makeCompConfig({
                                            componentDefinitions: [
                                                {
                                                    name: 'text_2',
                                                    component: { class: 'ContentComponent', config: makeCompConfig({}) }
                                                },
                                                {
                                                    name: "repeatable_2",
                                                    component: {
                                                        class: "RepeatableComponent", config: makeCompConfig({
                                                            elementTemplate: {
                                                                name: "",
                                                                component: {
                                                                    class: "GroupComponent", config: makeCompConfig({
                                                                        componentDefinitions: [
                                                                            {
                                                                                name: 'text_3',
                                                                                component: {
                                                                                    class: 'ContentComponent',
                                                                                    config: makeCompConfig({})
                                                                                }
                                                                            },
                                                                            {
                                                                                name: 'group_1',
                                                                                component: {
                                                                                    class: 'GroupComponent', config: makeCompConfig({
                                                                                        componentDefinitions: [
                                                                                            {
                                                                                                name: 'text_4',
                                                                                                component: {
                                                                                                    class: 'ContentComponent', config: makeCompConfig({})
                                                                                                }
                                                                                            },
                                                                                        ]
                                                                                    })
                                                                                },
                                                                                model: { class: "GroupModel", config: {} },
                                                                            },
                                                                        ]
                                                                    })
                                                                },
                                                                model: { class: "GroupModel", config: {} },
                                                            }
                                                        })
                                                    },
                                                    model: { class: "RepeatableModel", config: {} },
                                                }
                                            ]
                                        })
                                    },
                                    model: { class: "GroupModel", config: {} },
                                }
                            })
                        },
                    }
                ]
            };
            const recordMetadata = {
                text_1: "value text_1",
                repeatable_1: [
                    {
                        repeatable_2: [
                            {
                                text_3: "value repeatable_1.0.repeatable_2.0.text_3",
                                group_1: {
                                    text_4: "value repeatable_1.0.repeatable_2.0.group_1.text_4",
                                }
                            }
                        ]
                    },
                    {
                        text_2: "value repeatable_1.1.text_2",
                        repeatable_2: [
                            {
                                text_3: "value repeatable_1.1.repeatable_2.0.text_3",
                            }
                        ]
                    }
                ]
            };

            const original = JSON.stringify(formConfig);
            const result = await FormsService.buildClientFormConfig(formConfig, "view", null, recordMetadata);

            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);

            // confirm the client form config looks as expected
            expect(result.name).to.eql(expected.name);
            expect(result.componentDefinitions).to.have.length(2);
            expect(result.componentDefinitions[0].name).to.eql('text_1');
            expect(result.componentDefinitions[0].component.class).to.eql('ContentComponent');
            expect(result.componentDefinitions[1].name).to.eql('repeatable_1');
            expect(result.componentDefinitions[1].component.class).to.eql('ContentComponent');
            // done();
            // expect(result).to.eql(expected);
        });

        it('should build the expected config', async function () {
            const formConfig: FormConfigFrame = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                componentDefinitions: [
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        constraints: {
                            authorization: {
                                allowRoles: [],
                            },
                            allowModes: [],
                        },
                    }
                ]
            };
            const expected: FormConfigFrame = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                validators: [],
                validationGroups: {
                    all: { description: "Validate all fields with validators.", initialMembership: "all" },
                    none: { description: "Validate none of the fields.", initialMembership: "none" },
                },
                componentDefinitions: [
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                                autofocus: false,
                                cssClassesMap: {},
                                disabled: false,
                                editMode: true,
                                helpTextVisible: false,
                                helpTextVisibleOnInit: false,
                                labelRequiredStr: "*",
                                readonly: false,
                                visible: true,
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                value: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                            config: {
                                autofocus: false,
                                disabled: false,
                                editMode: true,
                                readonly: false,
                                type: "text",
                                visible: true,
                            },
                        },
                    }
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = await FormsService.buildClientFormConfig(formConfig, "edit");

            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);

            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
        });

        it('should hydrate group view-mode content from nested record data when group has no model', async function () {
            const formConfig: FormConfigFrame = {
                name: "basic-form",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                componentDefinitions: [
                    {
                        name: 'contributor_ci',
                        component: {
                            class: 'GroupComponent',
                            config: {
                                hostCssClasses: 'rb-form-contributor-inline',
                                componentDefinitions: [
                                    {
                                        name: 'name',
                                        layout: { class: 'InlineLayout', config: { label: 'Name' } },
                                        model: { class: 'SimpleInputModel', config: {} },
                                        component: { class: 'SimpleInputComponent', config: { type: 'text' } }
                                    },
                                    {
                                        name: 'email',
                                        layout: { class: 'InlineLayout', config: { label: 'Email' } },
                                        model: { class: 'SimpleInputModel', config: {} },
                                        component: { class: 'SimpleInputComponent', config: { type: 'text' } }
                                    },
                                    {
                                        name: 'orcid',
                                        layout: { class: 'InlineLayout', config: { label: 'ORCID' } },
                                        model: { class: 'SimpleInputModel', config: {} },
                                        component: { class: 'SimpleInputComponent', config: { type: 'text' } }
                                    }
                                ]
                            }
                        },
                        layout: { class: 'DefaultLayout', config: { label: 'contributor_ci' } }
                    }
                ]
            };

            const recordMetadata = {
                contributor_ci: {
                    name: "Brazz",
                    email: "b@b.com",
                    orcid: "0000-0000-0000-0001"
                }
            };

            const result = await FormsService.buildClientFormConfig(formConfig, "view", null, recordMetadata);
            const contributor = result.componentDefinitions?.[0];
            const content = (contributor?.component?.config as { content?: Record<string, string> } | undefined)?.content;

            expect(contributor?.component?.class).to.equal('ContentComponent');
            expect(content).to.deep.equal({
                name: "Brazz",
                email: "b@b.com",
                orcid: "0000-0000-0000-0001"
            });
        });
        it('should remove the component because the user does not have the required roles', async function () {
            const formConfig: FormConfigFrame = {
                name: "remove-item-constraint-roles",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                        },
                    },
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        constraints: {
                            authorization: {
                                allowRoles: ['Admin', 'Librarians'],
                            },
                            allowModes: [],
                        },
                    }
                ]
            };
            const expected: FormConfigFrame = {
                name: "remove-item-constraint-roles",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                validators: [],
                validationGroups: {
                    all: { description: "Validate all fields with validators.", initialMembership: "all" },
                    none: { description: "Validate none of the fields.", initialMembership: "none" },
                },
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                            config: {
                                autofocus: false,
                                disabled: false,
                                editMode: true,
                                readonly: false,
                                type: "text",
                                visible: true,
                            },
                        },
                        model: { class: "SimpleInputModel", config: {} }
                    }
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = await FormsService.buildClientFormConfig(formConfig, "edit");

            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);

            // confirm the client form config looks as expected
            expect(result.name).to.eql(expected.name);
            expect(result.componentDefinitions).to.have.length(1);
            expect(result.componentDefinitions[0].name).to.eql('text_1');
            expect(result.componentDefinitions[0].component.class).to.eql('SimpleInputComponent');
            // done();
            // expect(result).to.eql(expected);
        });
        it('should remove the component because the client does not have the required mode', async function () {
            const formConfig: FormConfigFrame = {
                name: "remove-item-constraint-mode",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        model: {
                            class: "SimpleInputModel",
                            config: {
                                defaultValue: 'text_1_value'
                            }
                        }
                    },
                    {
                        name: 'text_2',
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'TextField with default wrapper defined',
                                helpText: 'This is a help text',
                            }
                        },
                        model: {
                            class: 'SimpleInputModel',
                            config: {
                                defaultValue: 'hello world 2!',
                            }
                        },
                        component: {
                            class: 'SimpleInputComponent',
                        },
                        // expressions: {
                        //     'model.value': {
                        //         template: `<%= _.get(model,'text_1_event','') %>`
                        //     }
                        // },
                        constraints: {
                            authorization: {
                                allowRoles: [],
                            },
                            allowModes: ['edit'],
                        },
                    }
                ]
            };
            const expected: FormConfigFrame = {
                name: "remove-item-constraint-mode",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                validators: [],
                validationGroups: {
                    all: { description: "Validate all fields with validators.", initialMembership: "all" },
                    none: { description: "Validate none of the fields.", initialMembership: "none" },
                },
                componentDefinitions: [
                    {
                        name: 'text_1',
                        component: {
                            class: 'ContentComponent',
                            config: {
                                autofocus: false,
                                disabled: false,
                                editMode: true,
                                readonly: false,
                                visible: true,
                                content: "text_1_value",
                                template: "<span>{{content}}</span>",
                            },
                        },
                    },

                ]
            };
            const original = JSON.stringify(formConfig);
            const result = await FormsService.buildClientFormConfig(formConfig, "view");

            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);

            // confirm the client form config looks as expected
            expect(result).to.eql(expected);
        });
        it('should remove the components nested in repeatable and group components when the constraints are not met', async function () {
            const formConfig: FormConfigFrame = {
                name: "remove-items-constrains-nested",
                type: "rdmp",
                debugValue: true,
                domElementType: 'form',
                defaultComponentConfig: {
                    defaultComponentCssClasses: 'row',
                },
                editCssClasses: "redbox-form form",
                enabledValidationGroups: ["all"],
                componentDefinitions: [
                    {
                        name: 'repeatable_group_1',
                        model: {
                            class: 'RepeatableModel',
                            config: {
                                defaultValue: [{
                                    text_1: "value repeatable_group_1 defaultValue text_1",
                                    text_2: "value repeatable_group_1 defaultValue text_2",
                                    repeatable_for_admin: ["value repeatable_group_1 defaultValue repeatable_for_admin"],
                                }]
                            }
                        },
                        component: {
                            class: 'RepeatableComponent',
                            config: {
                                elementTemplate: {
                                    name: "",
                                    model: {
                                        class: 'GroupModel',
                                        config: {
                                            newEntryValue: {
                                                text_1: 'value repeatable_group_1 elementTemplate newEntryValue text_1',
                                                text_2: 'value repeatable_group_1 elementTemplate newEntryValue text_1',
                                                repeatable_for_admin: ["value repeatable_group_1 elementTemplate newEntryValue repeatable_for_admin"],
                                            }
                                        }
                                    },
                                    component: {
                                        class: 'GroupComponent',
                                        config: {
                                            wrapperCssClasses: 'col',
                                            componentDefinitions: [
                                                {
                                                    // requires mode edit, so expect to be removed
                                                    name: 'text_1',
                                                    model: { class: 'SimpleInputModel' },
                                                    component: { class: 'SimpleInputComponent' },
                                                    constraints: { allowModes: ['edit'] },
                                                },
                                                {
                                                    name: 'text_2',
                                                    model: { class: 'SimpleInputModel' },
                                                    component: { class: 'SimpleInputComponent' },
                                                },
                                                {
                                                    // requires role 'Admin', so is removed
                                                    name: 'repeatable_for_admin',
                                                    model: { class: 'RepeatableModel' },
                                                    component: {
                                                        class: 'RepeatableComponent',
                                                        config: {
                                                            elementTemplate: {
                                                                name: null,
                                                                model: {
                                                                    class: 'SimpleInputModel',
                                                                    config: { newEntryValue: 'hello world from repeatable for admin' }
                                                                },
                                                                component: { class: 'SimpleInputComponent' },
                                                                constraints: { authorization: { allowRoles: ['Admin'] } },
                                                            }
                                                        }
                                                    },
                                                }
                                            ]
                                        }
                                    },
                                    layout: {
                                        class: 'RepeatableElementLayout',
                                        config: { hostCssClasses: 'row align-items-start' }
                                    },
                                    // requires mode view, so is kept
                                    constraints: { authorization: { allowRoles: [] }, allowModes: ['view'] }
                                }
                            },
                        },
                        layout: {
                            class: 'DefaultLayout',
                            config: {
                                label: 'Repeatable TextField with default wrapper defined',
                                helpText: 'Repeatable component help text',
                            }
                        },
                    },
                ]
            };
            const original = JSON.stringify(formConfig);
            const result = await FormsService.buildClientFormConfig(formConfig, "view");

            // ensure the formConfig has not been modified
            expect(JSON.stringify(formConfig)).to.eql(original);

            // confirm nested constraints were applied before view-mode transform
            expect(result.componentDefinitions).to.have.length(1);
            expect(result.componentDefinitions[0].name).to.eql('repeatable_group_1');
            expect(result.componentDefinitions[0].component.class).to.eql('ContentComponent');
            expect(result.componentDefinitions[0].component.config.template).to.contain('<th>text_2</th>');
            expect(result.componentDefinitions[0].component.config.template).not.to.contain('text_1');
            expect(result.componentDefinitions[0].component.config.template).not.to.contain('repeatable_for_admin');
        });
    });
});
