import type { RouteAuthorization, ScopeKey } from './types';
import { preAuthAuthorization, publicAuthorization, scopeAuthorization } from './route-authorization';

const CORE_API_ACTION_SCOPES: Readonly<Record<string, string>> = Object.freeze({
  'webservice/AdminController#refreshCachedResources': 'app-config.manage',
  'webservice/AdminController#setAppConfig': 'app-config.manage',
  'webservice/AdminController#getAppConfig': 'app-config.manage',
  'webservice/AppConfigController#getAppConfig': 'app-config.manage',
  'webservice/AppConfigController#saveAppConfig': 'app-config.manage',
  'webservice/BrandingController#draft': 'branding.manage',
  'webservice/BrandingController#preview': 'branding.manage',
  'webservice/BrandingController#publish': 'branding.manage',
  'webservice/BrandingController#rollback': 'branding.manage',
  'webservice/BrandingController#logo': 'branding.manage',
  'webservice/BrandingController#favicon': 'branding.manage',
  'webservice/BrandingController#history': 'branding.manage',
  'webservice/DashboardConfigController#getConfigInfo': 'dashboard.configure',
  'webservice/DashboardConfigController#getDefaults': 'dashboard.configure',
  'webservice/DashboardConfigController#getOverrides': 'dashboard.configure',
  'webservice/DashboardConfigController#saveOverrides': 'dashboard.configure',
  'webservice/DashboardConfigController#getMergedConfig': 'dashboard.configure',
  'webservice/DashboardConfigController#saveWorkflowStateDashboardConfig': 'dashboard.configure',
  'webservice/DashboardConfigController#getMergedViewConfig': 'dashboard.configure',
  'webservice/DashboardConfigController#saveDashboardViewStepConfig': 'dashboard.configure',
  'webservice/DashboardConfigController#getMergedTypeFormatRules': 'dashboard.configure',
  'webservice/ExportController#downloadRecs': 'export.run',
  'webservice/FigshareCrosswalkController#list': 'vocabulary.manage',
  'webservice/FigshareCrosswalkController#create': 'vocabulary.manage',
  'webservice/FigshareCrosswalkController#usage': 'vocabulary.manage',
  'webservice/FigshareCrosswalkController#listLocalEntries': 'vocabulary.manage',
  'webservice/FigshareCrosswalkController#listMappings': 'vocabulary.manage',
  'webservice/FigshareCrosswalkController#saveMappings': 'vocabulary.manage',
  'webservice/FigshareCrosswalkController#approve': 'vocabulary.manage',
  'webservice/FigshareCrosswalkController#get': 'vocabulary.manage',
  'webservice/FigshareCrosswalkController#delete': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#listCatalogues': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#listSources': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#getSource': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#listSourceCategories': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#createSourcePreview': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#cloneSource': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#listSyncRuns': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#createPreview': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#getPreview': 'vocabulary.manage',
  'webservice/FigshareVocabularyController#applyPreview': 'vocabulary.manage',
  'webservice/FormManagementController#getForm': 'form.read',
  'webservice/FormManagementController#listForms': 'form.read',
  'webservice/HarvestRunController#listRuns': 'harvest.read',
  'webservice/HarvestRunController#getRun': 'harvest.read',
  'webservice/HarvestRunController#listRunEvents': 'harvest.read',
  'webservice/IntegrationAuditController#getAuditLog': 'integration.audit.read',
  'webservice/NamedQueryController#listQueries': 'named-query.manage',
  'webservice/NamedQueryController#getCollections': 'named-query.manage',
  'webservice/NamedQueryController#getQuery': 'named-query.manage',
  'webservice/NamedQueryController#createQuery': 'named-query.manage',
  'webservice/NamedQueryController#updateQuery': 'named-query.manage',
  'webservice/NamedQueryController#deleteQuery': 'named-query.manage',
  'EmailController#sendNotification': 'record.update',
  'webservice/RecordSchemaController#create': 'record.create',
  'webservice/RecordSchemaController#update': 'record.update',
  'webservice/RecordSchemaController#immutable': 'form.read',
  'webservice/RecordController#create': 'record.create',
  'webservice/RecordController#updateMeta': 'record.update',
  'webservice/RecordController#harvest': 'harvest.manage',
  'webservice/RecordController#legacyHarvest': 'harvest.manage',
  'webservice/RecordController#updateObjectMeta': 'record.update',
  'webservice/RecordController#getMeta': 'record.read',
  'webservice/RecordController#getRecordAudit': 'record.audit.read',
  'webservice/RecordController#listRecords': 'record.read',
  'webservice/RecordController#listDeletedRecords': 'record.read',
  'webservice/RecordController#getDeletedRecord': 'record.read',
  'webservice/RecordController#restoreRecord': 'record.restore',
  'webservice/RecordController#destroyDeletedRecord': 'record.destroy',
  'webservice/RecordController#getObjectMeta': 'record.read',
  'webservice/RecordController#deleteRecord': 'record.delete',
  'webservice/RecordController#addUserEdit': 'record.permission.manage',
  'webservice/RecordController#removeUserEdit': 'record.permission.manage',
  'webservice/RecordController#addUserView': 'record.permission.manage',
  'webservice/RecordController#removeUserView': 'record.permission.manage',
  'webservice/RecordController#addRoleEdit': 'record.permission.manage',
  'webservice/RecordController#removeRoleEdit': 'record.permission.manage',
  'webservice/RecordController#addRoleView': 'record.permission.manage',
  'webservice/RecordController#removeRoleView': 'record.permission.manage',
  'webservice/RecordController#getPermissions': 'record.permission.manage',
  'webservice/RecordController#addDataStreams': 'attachment.manage',
  'webservice/RecordController#getDataStream': 'attachment.read',
  'webservice/RecordController#listDatastreams': 'attachment.read',
  'webservice/RecordController#transitionWorkflow': 'record.update',
  'webservice/RecordTypeController#getRecordType': 'record-type.read',
  'webservice/RecordTypeController#listRecordTypes': 'record-type.read',
  'webservice/ReportController#executeNamedQuery': 'report.run',
  'webservice/ReportController#listConfigs': 'report.manage',
  'webservice/ReportController#getConfig': 'report.manage',
  'webservice/ReportController#createConfig': 'report.manage',
  'webservice/ReportController#updateConfig': 'report.manage',
  'webservice/ReportController#deleteConfig': 'report.manage',
  'webservice/ReportController#previewConfig': 'report.manage',
  'webservice/SearchController#search': 'search.execute',
  'webservice/SearchController#index': 'record.update.all',
  'webservice/SearchController#indexAll': 'record.update.all',
  'webservice/SearchController#removeAll': 'record.update.all',
  'webservice/TranslationController#listEntries': 'translation.manage',
  'webservice/TranslationController#getEntry': 'translation.manage',
  'webservice/TranslationController#setEntry': 'translation.manage',
  'webservice/TranslationController#deleteEntry': 'translation.manage',
  'webservice/TranslationController#getBundle': 'translation.manage',
  'webservice/TranslationController#setBundle': 'translation.manage',
  'webservice/UserManagementController#listUsers': 'user.read',
  'webservice/UserManagementController#getUser': 'user.read',
  'webservice/UserManagementController#searchLinkCandidates': 'user.account-link.manage',
  'webservice/UserManagementController#getUserLinks': 'user.account-link.manage',
  'webservice/UserManagementController#getUserAudit': 'user.read',
  'webservice/UserManagementController#linkAccounts': 'user.account-link.manage',
  'webservice/UserManagementController#createUser': 'user.manage',
  'webservice/UserManagementController#updateUser': 'user.manage',
  'webservice/UserManagementController#disableUser': 'user.manage',
  'webservice/UserManagementController#enableUser': 'user.manage',
  'webservice/UserManagementController#generateAPIToken': 'user.token.manage',
  'webservice/UserManagementController#revokeAPIToken': 'user.token.manage',
  'webservice/UserManagementController#listSystemRoles': 'authorization.role.read',
  'webservice/UserManagementController#createSystemRole': 'authorization.role.manage',
  'webservice/VocabularyController#list': 'vocabulary.read',
  'webservice/VocabularyController#import': 'vocabulary.manage',
  'webservice/VocabularyController#get': 'vocabulary.read',
  'webservice/VocabularyController#create': 'vocabulary.manage',
  'webservice/VocabularyController#update': 'vocabulary.manage',
  'webservice/VocabularyController#reorder': 'vocabulary.manage',
  'webservice/VocabularyController#delete': 'vocabulary.manage',
  'webservice/VocabularyController#sync': 'vocabulary.manage',
});

export function coreApiActionAuthorization(controller: string, action: string): RouteAuthorization | undefined {
  const scope = CORE_API_ACTION_SCOPES[`${controller}#${action}`];
  return scope === undefined ? undefined : scopeAuthorization(scope);
}

const PUBLIC_ROUTE_AUTHORIZATIONS: Readonly<Record<string, RouteAuthorization>> = Object.freeze({
  'get /dynamic/:asset': publicAuthorization('Application bootstrap asset.'),
  'get /:branding/:portal/dynamic/:asset': publicAuthorization('Brand application bootstrap asset.'),
  'get /:branding/:portal/styles/theme.css': publicAuthorization('Published brand stylesheet.'),
  'get /:branding/:portal/preview/:token([a-z0-9]+).css': publicAuthorization('Capability-token branding preview.'),
  'get /:branding/:portal/preview/:token.css': publicAuthorization('Capability-token branding preview.'),
  'get /:branding/:portal/images/logo': publicAuthorization('Published brand logo.'),
  'get /:branding/:portal/images/favicon': publicAuthorization('Published brand favicon.'),
  'get /:branding/:portal/locales/:lng/:ns.json': publicAuthorization('Published translation bundle.'),
  'get /:branding/:portal/locales/:lng/translation.json': publicAuthorization('Published translation bundle.'),
  'get /:branding/:portal/locales': publicAuthorization('Published language catalog.'),
});

const PRE_AUTH_ROUTE_AUTHORIZATIONS: Readonly<Record<string, RouteAuthorization>> = Object.freeze({
  'GET /csrfToken': preAuthAuthorization('CSRF bootstrap for browser sessions.'),
  'post /user/login_local': preAuthAuthorization('Local login submission.'),
  'post /user/login_aaf': preAuthAuthorization('AAF login callback.'),
  'get /user/login_oidc': preAuthAuthorization('OpenID Connect login callback.'),
  'HEAD /user/begin_oidc': preAuthAuthorization('Rejected OpenID Connect HEAD request.'),
  'get /user/begin_oidc': preAuthAuthorization('OpenID Connect login initiation.'),
  'get /:branding/:portal/user/login': preAuthAuthorization('Login page.'),
  'get /:branding/:portal/user/logout': preAuthAuthorization('Session logout.'),
});

const ROUTE_PATTERN_SCOPES: Readonly<Record<string, string>> = Object.freeze({
  'get /user/info': 'portal.profile.read',
  'get /:branding/:portal/user/info': 'portal.profile.read',
  '/:branding/:portal/home': 'portal.home.read',
  '/:branding/:portal/researcher/home': 'portal.home.read',
  '/:branding/:portal/record/search': 'search.execute',
  '/:branding/:portal/record/view-orig/:oid': 'record.read',
  '/:branding/:portal/admin': 'authorization.role.read',
  '/:branding/:portal/admin/translation': 'translation.manage',
  'get /:branding/:portal/admin/integrations/figshare/vocabularies': 'vocabulary.manage',
  '/:branding/:portal/availableServicesList': 'portal.home.read',
  '/:branding/:portal/getAdvice': 'portal.home.read',
  'get /:branding/:portal/admin/api-docs': 'authorization.scope.read',
  'get /:branding/:portal/admin/branding': 'branding.manage',
});

const ROUTE_ACTION_SCOPES: Readonly<Record<string, string>> = Object.freeze({
  'BrandingController#createPreview': 'branding.manage',
  'AdminController#harvestRunsIndex': 'harvest.read',
  'AdminController#rolesIndex': 'authorization.role.read',
  'AdminController#usersIndex': 'user.read',
  'AdminController#getUsers': 'user.read',
  'AdminController#updateUserDetails': 'user.manage',
  'AdminController#generateUserKey': 'user.token.manage',
  'AdminController#revokeUserKey': 'user.token.manage',
  'AdminController#addLocalUser': 'user.manage',
  'AdminController#searchLinkCandidates': 'user.account-link.manage',
  'AdminController#getUserLinks': 'user.account-link.manage',
  'AdminController#getUserAudit': 'user.read',
  'AdminController#linkAccounts': 'user.account-link.manage',
  'AdminController#disableUser': 'user.manage',
  'AdminController#enableUser': 'user.manage',
  'AdminController#getBrandRoles': 'authorization.role.read',
  'AdminController#updateUserRoles': 'authorization.assignment.manage',
  'DashboardConfigController#editor': 'dashboard.configure',
  'VocabularyController#manager': 'vocabulary.manage',
  'VocabularyController#list': 'vocabulary.read',
  'VocabularyController#import': 'vocabulary.manage',
  'VocabularyController#get': 'vocabulary.read',
  'VocabularyController#create': 'vocabulary.manage',
  'VocabularyController#update': 'vocabulary.manage',
  'VocabularyController#delete': 'vocabulary.manage',
  'VocabularyController#sync': 'vocabulary.manage',
  'UserController#profile': 'portal.profile.read',
  'UserController#find': 'user.read',
  'UserController#generateUserKey': 'user.token.manage',
  'UserController#revokeUserKey': 'user.token.manage',
  'UserController#update': 'user.manage',
  'DynamicAssetController#getFormCompiledItems': 'form.read',
  'DynamicAssetController#getAdminReportTemplates': 'report.run',
  'DynamicAssetController#getRecordDashboardTemplates': 'dashboard.read',
  'DynamicAssetController#getDashboardViewTemplates': 'dashboard.read',
  'BrandingAppController#config': 'branding.manage',
  'BrandingAppController#draft': 'branding.manage',
  'BrandingAppController#preview': 'branding.manage',
  'BrandingAppController#publish': 'branding.manage',
  'BrandingAppController#logo': 'branding.manage',
  'BrandingAppController#favicon': 'branding.manage',
  'RecordController#view': 'record.read',
  'RecordController#listWorkspaces': 'workspace.read',
  'RecordController#getMetaDefault': 'record.read',
  'RecordController#getMeta': 'record.read',
  'RecordController#getForm': 'form.read',
  'RecordController#search': 'search.execute',
  'RecordController#getAllTypes': 'record-type.read',
  'RecordController#getDashboardType': 'dashboard.read',
  'RecordController#getAllDashboardTypes': 'dashboard.read',
  'RecordController#getDashboardView': 'dashboard.read',
  'RecordController#getType': 'record-type.read',
  'RecordController#edit': 'record.update',
  'RecordController#delete': 'record.delete',
  'RecordController#getDeletedRecord': 'record.read',
  'RecordController#restoreRecord': 'record.restore',
  'RecordController#destroyDeletedRecord': 'record.destroy',
  'RecordController#doAttachment': 'attachment.manage',
  'RecordController#getDataStream': 'attachment.read',
  'RecordController#getAttachments': 'attachment.read',
  'RecordController#getPermissions': 'record.permission.manage',
  'RecordController#getRelatedRecords': 'record.read',
  'RecordController#getWorkflowSteps': 'record.update',
  'RecordController#create': 'record.create',
  'RecordController#update': 'record.update',
  'RecordController#stepTo': 'record.update',
  'RecordController#redirectLegacyConsolidatedDashboard': 'dashboard.read',
  'RecordController#render': 'dashboard.read',
  'RecordController#renderDashboardView': 'dashboard.read',
  'RecordController#getRecordList': 'record.read',
  'RecordController#getDeletedRecordList': 'record.read',
  'RecordController#renderDeletedRecords': 'record.read',
  'RecordAuditController#render': 'record.audit.read',
  'RecordAuditController#getAuditData': 'record.audit.read',
  'RecordAuditController#getPermissionsData': 'record.audit.read',
  'RecordAuditController#getIntegrationAuditData': 'integration.audit.read',
  'RecordAuditController#getIntegrationStatusData': 'integration.audit.read',
  'FormVocabularyController#get': 'vocabulary.read',
  'FormVocabularyController#expandPath': 'vocabulary.read',
  'FormVocabularyController#entries': 'vocabulary.read',
  'FormVocabularyController#children': 'vocabulary.read',
  'FormVocabularyController#getRecords': 'vocabulary.read',
  'FormVocabularyController#serviceEntries': 'vocabulary.read',
  'FormVocabularyController#externalEntries': 'vocabulary.read',
  'ExportController#index': 'export.run',
  'ExportController#downloadRecs': 'export.run',
  'AsynchController#start': 'workspace.manage',
  'AsynchController#stop': 'workspace.manage',
  'AsynchController#update': 'workspace.manage',
  'AsynchController#progress': 'workspace.read',
  'AsynchController#subscribe': 'workspace.read',
  'AsynchController#unsubscribe': 'workspace.read',
  'ReportsController#render': 'report.run',
  'ReportController#render': 'report.run',
  'ReportController#get': 'report.run',
  'ReportController#getResults': 'report.run',
  'ReportController#downloadCSV': 'report.run',
  'ReportController#listConfigs': 'report.manage',
  'ReportController#previewConfig': 'report.manage',
  'ReportController#getConfig': 'report.manage',
  'ReportController#createConfig': 'report.manage',
  'ReportController#updateConfig': 'report.manage',
  'ReportController#deleteConfig': 'report.manage',
  'BrandingController#renderApiB': 'authorization.scope.read',
  'BrandingController#renderSwaggerJSON': 'authorization.scope.read',
  'BrandingController#renderSwaggerYAML': 'authorization.scope.read',
  'ActionController#callService': 'record.update',
  'AppConfigController#getAppConfigForm': 'app-config.manage',
  'AppConfigController#saveAppConfig': 'app-config.manage',
  'AppConfigController#editAppConfig': 'app-config.manage',
  'NamedQueryController#editor': 'named-query.manage',
  'WorkspaceTypesController#getOne': 'workspace.read',
  'WorkspaceTypesController#get': 'workspace.read',
  'TranslationController#listEntriesApp': 'translation.manage',
  'TranslationController#setEntryApp': 'translation.manage',
  'TranslationController#getBundleApp': 'translation.manage',
  'TranslationController#setBundleApp': 'translation.manage',
  'webservice/TranslationController#updateBundleEnabled': 'translation.manage',
});

export function coreRouteAuthorization(
  routePattern: string,
  controller: string | undefined,
  action: string | undefined
): RouteAuthorization | undefined {
  const special = PUBLIC_ROUTE_AUTHORIZATIONS[routePattern] ?? PRE_AUTH_ROUTE_AUTHORIZATIONS[routePattern];
  if (special !== undefined) return special;

  const patternScope = ROUTE_PATTERN_SCOPES[routePattern];
  if (patternScope !== undefined) return scopeAuthorization(patternScope);

  if (controller === undefined || action === undefined) return undefined;
  const scope = ROUTE_ACTION_SCOPES[`${controller}#${action}`];
  return scope === undefined ? undefined : scopeAuthorization(scope);
}

export function declaredScope(authorization: RouteAuthorization): ScopeKey | undefined {
  return authorization.kind === 'scope' ? authorization.scope : undefined;
}
