import { isProxy } from 'node:util/types';
import {
  parseRecordDefinitionBrandId,
  parseRecordDefinitionKey,
  parseWorkflowStageKey,
  type PublishableRecordDefinitionAggregateDto,
  type PublishableWorkflowStageDto,
  type PublishableWorkflowTransitionDto,
  type RecordDefinitionActionBindingDto,
} from '@researchdatabox/sails-ng-common';
import { boundedValidationPreflight } from '../boundedValidation';
import { isRuntimeArray, isRuntimeRecord, type RuntimeRecord, type RuntimeValue } from '../runtimeValues';
import { migrateLegacyRecordAction, LegacyRecordActionMigrationError } from '../action-registry/legacyMigration';
import type { ActionBindingScope } from '../action-registry';
import { deriveWorkflowTransitionId } from './identifiers';
import { publishableRecordDefinitionAggregateSchema, RECORD_DEFINITION_CONTRACT_LIMITS } from './validation';
import { resolveAutomaticTransitionPlan } from '../workflow-transition/automatic';

/** Value-free diagnostics: paths are generated by this module, never copied from input keys. */
export class LegacyDatabaseMigrationError extends Error {
  constructor(
    readonly path: string,
    readonly code: string
  ) {
    super(`Record-definition migration rejected ${path}: ${code}.`);
    this.name = 'LegacyDatabaseMigrationError';
  }
}

function fail(path: string, code = 'unsupported-or-malformed-data'): never {
  throw new LegacyDatabaseMigrationError(path, code);
}

/** Reject executable own properties, including non-enumerable properties, before cloning. */
export function assertLegacyMigrationData(value: RuntimeValue): void {
  const preflight = boundedValidationPreflight(value, {
    maxBytes: 1_000_000,
    maxDepth: 48,
    maxStringLength: 32_768,
    maxPropertyNameLength: 128,
    maxWork: 50_000,
    arrayCardinalityLimit: () => 256,
    objectCardinalityLimit: () => 128,
  });
  if (!preflight.ok) fail('$', preflight.reason === 'prototype' ? 'unsafe-property' : 'unsafe-or-unbounded-data');
  const pending = [value];
  while (pending.length > 0) {
    const item = pending.pop();
    if (item === null || typeof item === 'string' || typeof item === 'boolean') continue;
    if (typeof item === 'number' && Number.isFinite(item)) continue;
    if (typeof item !== 'object' || isProxy(item)) fail('$', 'non-json-data');
    for (const key of Reflect.ownKeys(item)) {
      if (Array.isArray(item) && key === 'length') continue;
      if (typeof key !== 'string' || ['__proto__', 'prototype', 'constructor'].includes(key))
        fail('$', 'unsafe-property');
      const descriptor = Object.getOwnPropertyDescriptor(item, key);
      if (!descriptor?.enumerable || !Object.hasOwn(descriptor, 'value')) fail('$', 'unsafe-property');
      pending.push(descriptor.value);
    }
  }
}

function object(value: RuntimeValue, path: string): RuntimeRecord {
  if (!isRuntimeRecord(value)) return fail(path);
  return value;
}

function keys(value: RuntimeRecord, allowed: readonly string[], path: string): void {
  if (Object.keys(value).some(key => !allowed.includes(key))) fail(path, 'unsupported-property');
}

function text(value: RuntimeValue, path: string): string {
  if (typeof value !== 'string' || value.length === 0 || value.length > 256) return fail(path);
  return value;
}

function array(value: RuntimeValue, path: string): RuntimeValue[] {
  if (!isRuntimeArray(value)) return fail(path);
  return value;
}

function strings(value: RuntimeValue, path: string): string[] {
  return array(value, path).map(entry => text(entry, path));
}

function validationOperations(value: RuntimeValue, path: string): RuntimeRecord[] {
  if (value == null) return [];
  return Object.entries(object(value, path)).map(([name, entry], index) => {
    const location = `${path}[${index}]`;
    const operation = object(entry, location);
    keys(operation, ['enabledValidationGroups', 'roles', 'allowedTargetSteps', 'mode'], location);
    // Omitted groups inherit form-specific defaults; the aggregate requires an explicit set.
    if (operation.enabledValidationGroups === undefined)
      fail(location, 'inherited-validation-groups-require-explicit-mapping');
    return {
      name,
      enabledValidationGroups: operation.enabledValidationGroups,
      ...(operation.roles === undefined ? {} : { roles: operation.roles }),
      ...(operation.allowedTargetSteps === undefined ? {} : { allowedTargetStages: operation.allowedTargetSteps }),
      ...(operation.mode === undefined ? {} : { mode: operation.mode }),
    };
  });
}

function transferSettings(value: RuntimeValue): RuntimeRecord {
  if (value == null) return { fields: [], roleRules: [] };
  const transfer = object(value, '$.recordType.transferResponsibility');
  keys(transfer, ['fields', 'canEdit'], '$.recordType.transferResponsibility');
  const fields = Object.entries(object(transfer.fields, '$.recordType.transferResponsibility.fields')).map(
    ([field, entry], index) => {
      const path = `$.recordType.transferResponsibility.fields[${index}]`;
      const settings = object(entry, path);
      keys(settings, ['label', 'updateField', 'updateAlso', 'fieldNames'], path);
      return {
        field,
        label: settings.label,
        ...(settings.updateField === undefined ? {} : { updateField: settings.updateField }),
        updateAlso: settings.updateAlso ?? [],
        fieldNames:
          settings.fieldNames == null
            ? []
            : Object.entries(object(settings.fieldNames, `${path}.fieldNames`)).map(([name, target]) => ({
                name,
                field: target,
              })),
      };
    }
  );
  const roleRules = Object.entries(object(transfer.canEdit, '$.recordType.transferResponsibility.canEdit')).map(
    ([role, editableFields]) => ({ role, editableFields })
  );
  return { fields, roleRules };
}

export interface LegacyDatabaseTransformation {
  readonly brandId: string;
  readonly recordTypeKey: string;
  readonly recordTypeId: string;
  readonly definition: PublishableRecordDefinitionAggregateDto;
  readonly warnings: readonly string[];
  readonly workflowStepCount: number;
}

/** Pure shared preflight/up conversion. No application configuration or default-brand fallback. */
export function transformLegacyRecordDefinition(value: RuntimeValue): LegacyDatabaseTransformation {
  assertLegacyMigrationData(value);
  const envelope = object(value, '$');
  keys(envelope, ['recordType', 'workflowSteps'], '$');
  const row = object(envelope.recordType, '$.recordType');
  keys(
    row,
    [
      'id',
      'branding',
      'name',
      'key',
      'packageType',
      'searchCore',
      'searchable',
      'hooks',
      'searchFilters',
      'relatedTo',
      'transferResponsibility',
      'recordValidation',
      'concurrentModification',
      'dashboard',
      'actionPlan',
      'automaticTransitions',
    ],
    '$.recordType'
  );
  const recordTypeId = text(row.id, '$.recordType.id');
  const brandId = parseRecordDefinitionBrandId(text(row.branding, '$.recordType.branding'));
  const recordTypeKey = parseRecordDefinitionKey(text(row.name, '$.recordType.name'));
  for (const key of ['packageType', 'searchCore']) {
    if (row[key] !== undefined && row[key] !== null && typeof row[key] !== 'string') fail(`$.recordType.${key}`);
  }
  if (row.key !== `${brandId}_${recordTypeKey}`) fail('$.recordType.key');
  // Existing managed plans require an explicit reviewed migration; combining them with hooks is ambiguous.
  for (const key of ['actionPlan', 'dashboard']) {
    if (row[key] != null) fail(`$.recordType.${key}`, 'explicit-mapping-required');
  }
  const warnings = [
    'legacy-stage-stopping-preserved',
    'manual-transitions-require-source-edit-role',
    'labels-use-persisted-key',
  ];
  const transitionRoles = new Map<string, readonly string[]>();
  const stages: PublishableWorkflowStageDto[] = array(envelope.workflowSteps, '$.workflowSteps').map((entry, index) => {
    const path = `$.workflowSteps[${index}]`;
    const step = object(entry, path);
    keys(step, ['id', 'name', 'recordType', 'starting', 'hidden', 'config', 'form'], path);
    if (
      step.recordType !== recordTypeId ||
      (step.hidden !== undefined && step.hidden !== false) ||
      typeof step.starting !== 'boolean'
    )
      fail(path);
    if (step.id !== undefined) text(step.id, `${path}.id`);
    if (step.form != null && typeof step.form !== 'string') fail(`${path}.form`);
    const config = object(step.config, `${path}.config`);
    keys(
      config,
      ['workflow', 'authorization', 'form', 'displayIndex', 'baseRecordType', 'recordValidation'],
      `${path}.config`
    );
    const workflow = object(config.workflow, `${path}.config.workflow`);
    keys(workflow, ['stage', 'stageLabel'], `${path}.config.workflow`);
    if (workflow.stage !== step.name) fail(`${path}.config.workflow.stage`);
    const auth = object(config.authorization, `${path}.config.authorization`);
    keys(auth, ['viewRoles', 'editRoles', 'transitionRoles'], `${path}.config.authorization`);
    if (auth.transitionRoles !== undefined)
      transitionRoles.set(
        text(step.name, `${path}.name`),
        strings(auth.transitionRoles, `${path}.config.authorization.transitionRoles`)
      );
    const validation =
      config.recordValidation == null ? {} : object(config.recordValidation, `${path}.config.recordValidation`);
    keys(validation, ['operations'], `${path}.config.recordValidation`);
    if (
      config.displayIndex !== undefined &&
      (typeof config.displayIndex !== 'number' || !Number.isSafeInteger(config.displayIndex))
    )
      fail(`${path}.config.displayIndex`);
    return {
      schemaVersion: 1,
      key: parseWorkflowStageKey(text(step.name, `${path}.name`)),
      label: text(workflow.stageLabel, `${path}.config.workflow.stageLabel`),
      formReference: text(config.form, `${path}.config.form`),
      viewRoles: strings(auth.viewRoles, `${path}.config.authorization.viewRoles`),
      editRoles: strings(auth.editRoles, `${path}.config.authorization.editRoles`),
      displayOrder: typeof config.displayIndex === 'number' ? config.displayIndex : index,
      starting: step.starting,
      // Legacy workflows allowed a record to remain at every stage indefinitely.
      terminal: true,
      validationOverrides: validationOperations(
        validation.operations,
        `${path}.config.recordValidation.operations`
      ) as object as PublishableWorkflowStageDto['validationOverrides'],
      ...(config.baseRecordType === undefined
        ? {}
        : {
            baseRecordTypeKey: parseRecordDefinitionKey(text(config.baseRecordType, `${path}.config.baseRecordType`)),
          }),
    };
  });
  const transitions: PublishableWorkflowTransitionDto[] = [];
  if (stages.length * (stages.length - 1) > RECORD_DEFINITION_CONTRACT_LIMITS.maxTransitions)
    fail('$.workflowSteps', 'expanded-transition-limit');
  const appendTransition = (transition: PublishableWorkflowTransitionDto): void => {
    if (transitions.length >= RECORD_DEFINITION_CONTRACT_LIMITS.maxTransitions)
      fail('$.workflowSteps', 'expanded-transition-limit');
    transitions.push(transition);
  };
  for (const source of stages)
    for (const target of stages) {
      if (source.key === target.key) continue;
      const allowedRoles = transitionRoles.get(target.key);
      if (!allowedRoles?.length)
        fail('$.workflowSteps', 'unrestricted-legacy-transitions-require-explicit-role-mapping');
      appendTransition({
        schemaVersion: 1,
        id: deriveWorkflowTransitionId({ brandId, recordTypeKey, stableKey: `legacy-${source.key}-${target.key}` }),
        sourceStageKey: source.key,
        targetStageKey: target.key,
        label: target.label,
        mode: 'manual',
        allowedRoles,
      });
    }
  const actionBindings: RecordDefinitionActionBindingDto[] = [];
  let bindingBytes = 0;
  if (row.automaticTransitions != null) {
    const plan = resolveAutomaticTransitionPlan({ automaticTransitions: row.automaticTransitions }, recordTypeKey);
    for (const { definition } of plan.transitions) {
      const target = stages.find(stage => stage.key === definition.targetStage);
      if (
        !target ||
        (definition.targetStageLabelCheck !== undefined && target.label !== definition.targetStageLabelCheck) ||
        (definition.targetFormCheck !== undefined && target.formReference !== definition.targetFormCheck)
      )
        fail('$.recordType.automaticTransitions', 'transition-target-mismatch');
      appendTransition({
        schemaVersion: 1,
        id: deriveWorkflowTransitionId({ brandId, recordTypeKey, stableKey: definition.id }),
        sourceStageKey: parseWorkflowStageKey(definition.sourceStage),
        targetStageKey: target.key,
        label: target.label,
        mode: 'automatic',
        event: definition.event,
        priority: definition.priority,
        condition: definition.condition,
        ...(definition.validationOperation === undefined
          ? {}
          : { validationOperation: definition.validationOperation }),
      });
    }
  }
  // A10 explicit edges already ran transition hooks; legacy mutating hooks did not.
  const explicitTransitionIds = new Set(
    transitions.filter(transition => transition.mode === 'automatic').map(transition => transition.id)
  );
  const hooks = row.hooks == null ? {} : object(row.hooks, '$.recordType.hooks');
  keys(hooks, ['onCreate', 'onUpdate', 'onDelete', 'onTransitionWorkflow'], '$.recordType.hooks');
  for (const mode of ['onCreate', 'onUpdate', 'onDelete', 'onTransitionWorkflow'] as const) {
    if (hooks[mode] === undefined) continue;
    const phases = object(hooks[mode], `$.recordType.hooks.${mode}`);
    keys(phases, ['pre', 'postSync', 'post'], `$.recordType.hooks.${mode}`);
    for (const phase of ['pre', 'postSync', 'post'] as const) {
      if (phases[phase] === undefined) continue;
      const declarations = array(phases[phase], `$.recordType.hooks.${mode}.${phase}`);
      const scopes: ActionBindingScope[] =
        mode === 'onTransitionWorkflow'
          ? transitions
              .filter(transition => transition.mode === 'manual' || explicitTransitionIds.has(transition.id))
              .map(transition => ({ context: 'workflow-transition', mode, phase, scopeId: transition.id }))
          : [{ context: 'record-lifecycle', mode, phase }];
      if (scopes.length === 0 && declarations.length > 0)
        fail(`$.recordType.hooks.${mode}.${phase}`, 'unrepresentable-transition-hooks');
      for (const scope of scopes)
        for (let index = 0; index < declarations.length; index++) {
          const path = `$.recordType.hooks.${mode}.${phase}[${index}]`;
          try {
            const converted = migrateLegacyRecordAction({
              schemaVersion: 1,
              recordTypeKey,
              scope,
              stableKey: `legacy-${mode}-${phase}-${index}`,
              order: index,
              sourcePath: path,
              definition: declarations[index],
            });
            if (converted.kind === 'automatic-transition') {
              if (phase !== 'pre') fail(path, 'automatic-transition-requires-pre');
              if (index !== declarations.length - 1)
                fail(path, 'interleaved-automatic-transition-requires-explicit-mapping');
              const target = stages.find(stage => stage.key === converted.targetStage);
              if (
                !target ||
                (converted.targetStageLabelCheck !== undefined && target.label !== converted.targetStageLabelCheck) ||
                (converted.targetFormCheck !== undefined && target.formReference !== converted.targetFormCheck)
              )
                fail(path, 'transition-target-mismatch');
              appendTransition({
                schemaVersion: 1,
                id: deriveWorkflowTransitionId({ brandId, recordTypeKey, stableKey: converted.id }),
                sourceStageKey: parseWorkflowStageKey(converted.sourceStage),
                targetStageKey: target.key,
                label: target.label,
                mode: 'automatic',
                event: converted.event,
                priority: converted.priority,
                condition: converted.condition,
              });
            } else {
              for (const binding of converted.bindings) {
                if (binding.scope.context === 'queued-record-action') fail(path);
                bindingBytes += Buffer.byteLength(JSON.stringify(binding), 'utf8');
                if (
                  actionBindings.length >= RECORD_DEFINITION_CONTRACT_LIMITS.maxActionBindings ||
                  bindingBytes > 262_144
                )
                  fail(path, 'expanded-binding-limit');
                actionBindings.push(binding as RecordDefinitionActionBindingDto);
              }
            }
          } catch (error) {
            if (error instanceof LegacyRecordActionMigrationError) fail(path, error.code);
            throw error;
          }
        }
    }
  }
  const validation = row.recordValidation == null ? {} : object(row.recordValidation, '$.recordType.recordValidation');
  keys(validation, ['mode', 'operations'], '$.recordType.recordValidation');
  const filters =
    row.searchFilters == null
      ? []
      : array(row.searchFilters, '$.recordType.searchFilters').map((entry, index) => {
          const path = `$.recordType.searchFilters[${index}]`;
          const filter = object(entry, path);
          keys(filter, ['name', 'title', 'type', 'typeLabel', 'alwaysActive'], path);
          return {
            id: `legacy-filter-${index}`,
            field: filter.name,
            title: filter.title,
            kind: filter.type,
            typeLabel: filter.typeLabel ?? null,
            alwaysActive: filter.alwaysActive ?? false,
          };
        });
  const relationships =
    row.relatedTo == null
      ? []
      : array(row.relatedTo, '$.recordType.relatedTo').map((entry, index) => {
          const path = `$.recordType.relatedTo[${index}]`;
          const relation = object(entry, path);
          keys(
            relation,
            ['id', 'label', 'recordType', 'localField', 'foreignField', 'cardinality', 'direction', 'includeByDefault'],
            path
          );
          return {
            id: relation.id ?? `legacy-relation-${index}`,
            ...(relation.label === undefined ? {} : { label: relation.label }),
            targetRecordTypeKey: relation.recordType,
            localField: relation.localField ?? 'redboxOid',
            foreignField: relation.foreignField,
            cardinality: relation.cardinality ?? 'many',
            direction: relation.direction ?? 'outbound',
            includeByDefault: relation.includeByDefault ?? false,
          };
        });
  const parsed = publishableRecordDefinitionAggregateSchema.safeParse({
    schemaVersion: 1,
    definitionState: 'publishable',
    recordType: {
      labels: { name: recordTypeKey, namePlural: recordTypeKey },
      searchable: row.searchable ?? false,
      searchFilters: filters,
      relationships,
      transferResponsibility: transferSettings(row.transferResponsibility),
      validation: {
        mode: validation.mode ?? 'shadow',
        operations: validationOperations(validation.operations, '$.recordType.recordValidation.operations'),
      },
      concurrency: row.concurrentModification ?? { mode: 'last-write-wins' },
    },
    stages,
    transitions,
    actionBindings,
  });
  if (!parsed.success) fail('$', 'invalid-transformed-aggregate');
  return { brandId, recordTypeKey, recordTypeId, definition: parsed.data, warnings, workflowStepCount: stages.length };
}
